---
# DEB sources and packages

deb_sources: []

deb_packages:
  - mutt                      # mail client
  - notmuch                   # mail indexer
  - offlineimap3              # mail syncing software
  - ffmpeg
  - graphicsmagick
  - graphicsmagick-imagemagick-compat
  - weechat                   # irc client
  - xdg-user-dirs
  - mc                        # file manager
  - direnv                    # load .env files
  - fzf                       # fuzzy finder
  - python3-fontforge         # required to build Nerdfonts
  - figlet
  - ttyrec                    # tty recording
  - ttygif
