---
# User-level directories

# This is shared both by Linux and Windows as I tend to have same home
# directory organization on both systems. On Windows especially there's a lot
# of littering done by Apps so I redirect Documents and all special folders to
# windocs.

# Properties explanation:
#   path: is relatvie to ~ or %USERPROFILE%
#   owner: (Linux only)
#   group: (Linux only)
#   mode: (Linux only)
#   state: directory, absent, link, skip
#   link: "/mnt/c/..." symlink
#   win_link: "\\wsl.localhost\debian..." junction link to
#   win_guid: (Windows only) GUID of special directory
#   win_icon: (Windows only) icon of directory
#   xdg: "FOO" will set "XDG_FOO_DIRECTORY" ~/.config/user-dirs.dirs or
#        environment variable on Windows

#
#
# link: "wsl" will link %USERPROFILE%/path to WSL (dirs.yml)
# link: "windows" will link //wsl.local../path to Windows (win_dirs.yml)
# os: "windows" (or "linux") will create directory only on given OS

# BUG: This DOES NOT work when my_facts.wsl_home_is_userprofile; if that sweet
# moment ever comes back, this needs fixing.
# WARN: Directories are created and deleted in When nesting parent directory
# has to go first.
user_dirs:
  - path: "bak"                       # backups
  - path: "desk"                      # desktop (wsl -> win)
    state: "{{ 'link' if my_facts.is_wsl and ansible_facts.system in ('Linux',) else 'directory' }}"
    link: "{{ my_facts.wsl_userprofile_dir + '/desk' if ansible_facts.system in ('Linux',) else omit }}"
    xdg: "XDG_DESKTOP_DIR"
    win_guid: "B4BFCC3A-DB2C-424C-B029-7FE99A87C641"
    win_icon: "%SystemRoot%\\system32\\imageres.dll,-183"
  - path: "docs"                      # docs (docs -> ~/docs)
    state: "{{ 'link' if my_facts.is_wsl and ansible_facts.system in ('Linux',) else 'directory' }}"
    link: "{{ my_facts.wsl_userprofile_dir + '/docs' if ansible_facts.system in ('Linux',) else omit }}"
    xdg: "XDG_DOCUMENTS_DIR"
    win_icon: "%SystemRoot%\\system32\\imageres.dll,-112"
  - path: "drive"                     # drive (wsl -> win)
    state: "{{ 'link' if my_facts.is_wsl and ansible_facts.system in ('Linux',) else 'directory' }}"
    link: "{{ my_facts.wsl_userprofile_dir + '/drive' if ansible_facts.system in ('Linux',) else omit }}"
    win_icon: "%USERPROFILE%\\.local\\share\\pixmaps\\folder_drive.ico,0"
  # Google Drive related directories
  # TODO:
  - path: "logs"                      # logs (irc, etc.)
    state: "{{ 'skip' if ansible_facts.os_family in ('Windows',) else 'directory' }}"
  - path: "mail"                      # maildir
    state: "{{ 'skip' if ansible_facts.os_family in ('Windows',) else 'directory' }}"
  - path: "downl"                     # downloads (wsl -> win)
    state: "{{ 'link' if my_facts.is_wsl and ansible_facts.system in ('Linux',) else 'directory' }}"
    link: "{{ my_facts.wsl_userprofile_dir + '/downl' if ansible_facts.system in ('Linux',) else omit }}"
    xdg: "XDG_DOWNLOAD_DIR"
    win_guid: "374DE290-123F-4565-9164-39C4925E467B"
    win_icon: "%SystemRoot%\\system32\\imageres.dll,-184"
  - path: "downl/arch"                # downloads archive
    state: "{{ 'skip' if my_facts.is_wsl and ansible_facts.system in ('Linux',) else 'directory' }}"
  - path: "music"                     # music (wsl -> win)
    state: "{{ 'link' if my_facts.is_wsl and ansible_facts.system in ('Linux',) else 'directory' }}"
    link: "{{ my_facts.wsl_userprofile_dir + '/music' if ansible_facts.system in ('Linux',) else omit }}"
    xdg: "XDG_MUSIC_DIR"
    win_guid: "4BD8D571-6D19-48D3-BE97-422220080E43"
    win_icon: "%SystemRoot%\\system32\\imageres.dll,-108"
  - path: "pics"                      # pictures (wsl -> win)
    state: "{{ 'link' if my_facts.is_wsl and ansible_facts.system in ('Linux',) else 'directory' }}"
    link: "{{ my_facts.wsl_userprofile_dir + '/pics' if ansible_facts.system in ('Linux',) else omit }}"
    xdg: "XDG_PICTURES_DIR"
    win_guid: "33E28130-4E1E-4676-835A-98395C3BC3BB"
    win_icon: "%SystemRoot%\\system32\\imageres.dll,-113"
  - path: "videos"                    # videos (wsl -> win)
    state: "{{ 'link' if my_facts.is_wsl and ansible_facts.system in ('Linux',) else 'directory' }}"
    link: "{{ my_facts.wsl_userprofile_dir + '/videos' if ansible_facts.system in ('Linux',) else omit }}"
    xdg: "XDG_VIDEOS_DIR"
    win_guid: "18989B1D-99B5-455B-841C-AB7C74E4DDFC"
    win_icon: "%SystemRoot%\\system32\\imageres.dll,-189"
  - path: "src"                       # source code
    xdg: "XDG_SRC_DIR"
    win_icon: "%USERPROFILE%\\.local\\share\\pixmaps\\folder_src.ico,0"
  - path: "src\\wsl"                  # linux source code (win -> wsl _ONLY_)
    state: "{{ 'link' if my_facts.is_wsl and ansible_facts.os_family in ('Windows',) else 'skip' }}"
    link: "{{ my_facts.wsl_unc_home_dir + '\\src' }}"
  - path: "src/win"                   # windows source code (wsl -> win _ONLY_)
    state: "{{ 'link' if my_facts.is_wsl and ansible_facts.system in ('Linux',) else 'skip' }}"
    link: "{{ my_facts.wsl_userprofile_dir + '/src' }}"
  - path: "pub"                       # public files
    state: "{{ 'skip' if ansible_facts.os_family in ('Windows',) else 'directory' }}"
    xdg: "XDG_PUBLICSHARE_DIR"
  - path: "public_html"               # local web
    state: "{{ 'skip' if ansible_facts.os_family in ('Windows',) else 'directory' }}"
  - path: "tmpl"                      # templates
    # WARN: This directory is in dotfiles
    xdg: "XDG_TEMPLATES_DIR"
  # NOTE: Various apps are polluting My Documents with their data so I move the
  # entire directory to AppData and consider a data directory.
  - path: "AppData\\Documents"
    state: "{{ 'directory' if ansible_facts.os_family in ('Windows',) else 'skip' }}"
    win_guid: "FDD39AD0-238F-46AF-ADB4-6C85480369C7"


# WSL native directories
# NOTE: These need to be on native WSL filesystem in case HOME is on NTFS
wsl_native_dirs:
  - src: "/home/{{ my_user.username }}/.ssh/ctrl"
    dest: "{{ my_user.home }}/.ssh/ctrl"
    mode: "0700"
