---
# Remove and disable Snap from the system

- name: Removing snap APT packages
  apt:
    pkg:
      - snapd
      - gnome-software-plugin-snap
    state: absent
    purge: true

- name: Preventing snap packages from being further installed
  dpkg_selections:
    name: snapd
    selection: hold

# NOTE: In upgraded installations of Ubuntu this file can be left over and
# cause APT to not operate properly.
- name: Removing /etc/apt/apt.conf.d/20snapd.conf
  file:
    path: /etc/apt/apt.conf.d/20snapd.conf
    state: absent
  when:
    - "\"snapd\" not in ansible_facts.packages"

- name: Removing snap files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /snap
    - /var/snap
    - /var/lib/snap
    - /var/cache/snapd
