---
# Disable OneDrive for all users

- name: Disabling OneDrive policies
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "dword"
  with_items:
    # Disable OneDrive group policies
    - path: "HKLM:\\SOFTWARE\\Wow6432Node\\Policies\\Microsoft\\Windows\\OneDrive"
      name: "DisableFileSyncNGSC"
      data: 0x00000001
    - path: "HKLM:\\SOFTWARE\\Wow6432Node\\Policies\\Microsoft\\Windows\\OneDrive"
      name: "DisableFileSync"
      data: 0x00000001
    # Remove Explorer.exe sidebar
    - path: "HKCR:\\CLSID\\{018D5C66-4533-4307-9B53-224DE2ED1FE6}"
      name: "System.IsPinnedToNameSpaceTree"
      data: 0x00000000
    - path: "HKCR:\\Wow6432Node\\CLSID\\{018D5C66-4533-4307-9B53-224DE2ED1FE6}"
      name: "System.IsPinnedToNameSpaceTree"
      data: 0x00000000
  loop_control:
    label: "{{ item.path }}.{{ item.name }}={{ item.data }}"

- name: Uninstalling OneDrive client
  win_shell: |
    $paths = @("$env:SYSTEMROOT\System32\OneDriveSetup.exe", "$env:SYSTEMROOT\SysWOW64\OneDriveSetup.exe")
    foreach ($p in $paths) {
      if (Test-Path $p) {
        & $p /uninstall
      }
    }
  register: out
  changed_when: false
