---
# Configure WSL

# This configures WSL to maintain file metadata even on native filesystems. If
# system is WSL it creates /etc/wsl.conf if it didn't exist. If file is created
# LxssManager service is also restarted for changes to come into effect.

# This is to get /tmp cleared on reboot
- name: Converting /tmp to tmpfs
  lineinfile:
    path: /etc/fstab
    regexp: "^tmpfs	/tmp	tmpfs	defaults	1 0$"
    line: "tmpfs	/tmp	tmpfs	defaults	1 0"
  register: out_wsl_tmpfs
  when:
    - my_facts.is_wsl == 1

- name: Installing wsl.conf
  copy:
    src: "{{ role_path }}/files/wsl.conf"
    dest: "/etc/wsl.conf"
    owner: root
    group: root
    mode: 644
    force: yes
  register: out_wsl_wslconf
  when:
    - my_facts.is_wsl is defined

# NOTE This will result in interactive prompt, since this playbook is for
# interactive use on WSL it doesn't matter much.
- name: Rebooting WSL
  command: >
    /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
    Start-Process
    -FilePath "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
    -ArgumentList "Restart-Service","LxssManager"
    -Verb runas
  when: 
    - (out_wsl_tmpfs.changed or out_wsl_wslconf.changed)
    - my_facts.is_wsl is defined

# NOTE SysV IPC doesn't work on WSL 1, fakeroot needs to use TCP instead.
- name: Switching to fakeroot-tcp
  command: >
    update-alternatives --set fakeroot /usr/bin/fakeroot-tcp
  when:
    - my_facts.is_wsl == 1
