---
# Configure Linux side of WSL based system

# This configures WSL to maintain file metadata even on native filesystems. If
# system is WSL it creates /etc/wsl.conf if it didn't exist. If file is created
# LxssManager service is also restarted for changes to come into effect.

# This is to get /tmp cleared on reboot
- name: Converting /tmp to tmpfs
  lineinfile:
    path: /etc/fstab
    regexp: "^tmpfs	/tmp	tmpfs	defaults	1 0$"
    line: "tmpfs	/tmp	tmpfs	defaults	1 0"
  register: out_wsl_tmpfs
  when:
    - my_facts.is_wsl

- name: Installing wsl.conf
  copy:
    src: "{{ role_path }}/files/wsl.conf"
    dest: "/etc/wsl.conf"
    owner: root
    group: root
    mode: 644
    force: yes
  register: out_wsl_wslconf
  when:
    - my_facts.is_wsl

- name: Warning about WSL restart
  pause:
    prompt: |
      Windows Subsystem for Linux (WSL) configuration was changed and in order
      to continue the playbook it needs to be restarted so that change take
      effect.

      After pressing ENTER WSL will be terminated. Close the terminal and run
      it again to restart WSL. Then re-run playbook.
  when:
    - (out_wsl_tmpfs.changed or out_wsl_wslconf.changed)
    - my_facts.is_wsl

- name: Restarting WSL
  command: /mnt/c/Windows/System32/wsl.exe -t $WSL_DISTRO_NAME
  when: 
    - (out_wsl_tmpfs.changed or out_wsl_wslconf.changed)
    - my_facts.is_wsl
