---
# Variables for all host groups.
# See README.md in ansible/ directory for further explanation.

# Settings
dotfiles: blami/dotfiles.git
ntp: time.cloudflare.com

# User
# NOTE: This is shared by both Linux and Windows tasks but separated using win_
# prefix.
my_user:
  # -e username=NAME
  username: "blami"
  gecos: "Ondrej Balaz,,,,blami@blami.net"
  shell: "/usr/bin/zsh"
  # NOTE: relative to ~/.ssh/
  ssh_key: "keys/id_blami_rsa"
  # -e home=PATH
  # NOTE: empty defaults to /home/{{ my_user.username }}
  home:
  groups:
    - adm
    - dialout
    - cdrom
    - floppy
    - audio
    - dip
    - video
    - plugdev
    - netdev
    - sudo
  umask: "002"
  # is_local applies to both Linux and Windows (AD)
  is_local: true
  # -e win_username=NAME
  win_username: "blami"
  win_domain_username:
  # NOTE: empty defaults to C:\Users\{{ my_user.win_username }}
  win_userprofile:
  is_msaccount: false

# Facts
# NOTE: This is shared by both Linux and Windows tasks.
my_facts:
  # tasks/pre_user.yml
  has_my_user: false
  has_become_my_user: false
  has_become_root: false
  has_administrator: false
  # tasks/pre_linux.yml
  has_systemd: false
  # tasks/pre_wsl.yml, roles/os/tasks/wsl.yml
  is_wsl: false
  has_wsl_interop: false
  wsl_distro:
  wsl_powershell:
  wsl_unc_home_dir:
  wsl_unc_playbook_dir:
  wsl_userprofile_dir:
  wsl_unc_userprofile_dir:
  wsl_version:
  wsl_windrive_dir:
  wsl_home_is_userprofile: false
  wsl_host_hostname:
  wsl_host_ip:
  wsl_guest_ip:
  # tasks/post_wsl.yml
  can_winrm: false
  # tasks/pre_windows.yml
  has_choco: false

# Control Node Facts
my_control_node_facts:
  # tasks/pre_user.yml
  has_become_root: false
  # roles/_common/bitwarden.yml
  has_bitwarden: false
  has_bitwarden_unlocked: false
  bitwarden_session:


# Ansible
# NOTE: my_cache_dir is overriden by tasks/pre_ansible.yml if
# /var/cache/ansible can be created or already exists. /tmp is just fallback.
my_control_node_cache_dir: /tmp
my_cache_dir: /tmp
