---
ntp_server: time.cloudflare.com

# LAN related variables
my_lan:
  check_host: router.lan.blami.net
  printer: printer.w.lan.blami.net
  install_unc: "\\\\fs.lan.blami.net\\export\\data\\install"
