---
my_user:
  # These are defaults for user to be created; if user exists and has different
  # settings, or if playbook is run with -e user=FOO those variables are
  # overriden in tasks/pre_linux.yml
  username: "blami"
  gecos: "Ondrej Balaz,,,,blami@blami.net"
  shell: "/usr/bin/zsh"
  home: "/home/blami"
  groups:
    - adm
    - dialout
    - cdrom
    - floppy
    - sudo
    - audio
    - dip
    - video
    - plugdev
    - netdev
    # NOTE: DO NOT put non-system (such as docker) groups here
  umask: "002"
  # Relative to {{ my_user.home }}/.ssh
  ssh_key: "keys/id_blami_rsa"
