---
# Add RPM sources

- name: Adding RPM Sources
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.desc }}"
    baseurl: "{{ item.repo }}"
    gpgkey: "{{ item.key }}"
  loop_control:
    label: "{{ item.name }}"
  with_items:
    - "{{ rpm_sources }}"
  when:
    - ansible_facts.os_family == "RedHat"
  tags: debug
