---
# Install Chocolatey packages

# NOTE: Tasks here rely on WSL UNC path being accessible. With 'certificate'
# WinRM auth this requires become_user: DOMAIN\USER (see os/tasks/main.yml). If
# performed as become_user: System this won't work.

- name: Packing Local Chocolatey Packages
  win_shell: |
    Get-ChildItem -Path {{ my_facts.choco_source }} -Filter *.nuspec -Recurse | ForEach-Object {
      & choco pack $_.FullName
      if($LASTEXITCODE -ne 0) { Write-Host $_.Name ; Exit 1 }
    }
  args:
    chdir: "{{ my_facts.choco_source }}"
  when:
    - "'has_choco' in my_facts"
    - my_facts.has_choco

- name: Installing Local Chocolatey Packages
  win_chocolatey:
    name: "{{ item.name if (item | xis_dict) else item }}"
    state: "{{ item.state if (item | xis_dict) else 'latest' }}"
  loop_control:
    label: "{{ item.name if (item | xis_dict) else item }}"
  with_items: "{{ windows_choco_packages }}"
  when:
    - "'has_choco' in my_facts"
    - my_facts.has_choco
