---
# Install Chocolatey packages

# NOTE: Tasks here rely on WSL UNC path being accessible. With 'certificate'
# WinRM auth this requires become_user: DOMAIN\USER (see os/tasks/main.yml). If
# performed as become_user: SYSTEM this won't work.

- name: Packing Local Chocolatey Packages
  win_shell: |
    Get-ChildItem -Path {{ my_facts.choco_source }} -Filter *.nuspec -Recurse | ForEach-Object {
      & choco pack $_.FullName
      if($LASTEXITCODE -ne 0) { Write-Host $_.Name ; Exit 1 }
    }
  args:
    chdir: "{{ my_facts.choco_source }}"
  when:
    - "'has_choco' in my_facts"
    - my_facts.has_choco

- name: Installing Local Chocolatey Packages
  win_chocolatey:
    name: "{{ item }}"
    # NOTE: This should work with 0.0 self updating packages as we never change
    # their version.
    state: "latest"
  loop_control:
    label: "{{ item }}"
  # If host is in LAN install also LAN hosted packages (if defined)
  with_items: "{{ (my_facts.has_lan | default(false)) | ternary(windows_choco_packages + (windows_choco_packages_lan | default([])), windows_choco_packages) }}"
  when:
    - "'has_choco' in my_facts"
    - my_facts.has_choco
