---
# Add or edit registry keys

- name: Setting Windows Registry Keys
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "{{ item.type }}"
  loop_control:
    label: "{{ item.path }}.{{ item.name }}={{ item.data}}"
  with_items: "{{ windows_reg }}"
