---
# Set environment variables and add directories to PATH

- name: Setting Environment Variables
  win_environment:
    level: system
    state: present
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ windows_env }}"
  loop_control:
    label: "{{ item.key }}={{ item.value}}"
  when:
    - windows_env

# TODO: Use win_path to add machine and user PATH variables
#- name: Adding Directories PATH
#  win_path:
