---
# Setup Docker

- name: Adding User {{ my_user.username }} To Group docker
  user:
    name: "{{ my_user.username }}"
    groups: docker
    append: true
  when:
    - "'docker-ce' in ansible_facts.packages"

- name: Enabling Docker systemd Unit
  systemd:
    name: "docker"
    daemon_reload: true
    enabled: true
    state: started
  when:
    - my_facts.has_systemd
    - "'docker-ce' in ansible_facts.packages"
