---
# On WSL1 change fakeroot to fakeroot-tcp to avoid not implemented SysV IPC
# calls.

- name: Switching to fakeroot-tcp
  command: >
    update-alternatives --set fakeroot /usr/bin/fakeroot-tcp
  when:
    - my_facts.is_wsl == 1
    - "'fakeroot' in ansible_facts.packages"
    - ansible_facts.os.family == "Debian"
