---
# Setup Go development environment and install packages

# In order to get GOPATH right (as defined in .profile.d/golang.sh) we need to
# source that file (and hence provide pathmunge() kludge)

- name: Detecting Go
  command: go version
  failed_when: false
  changed_when: false
  register: has_go

- name: Installing Go Packages To GOPATH
  shell:
    chdir: "{{ my_user.home }}"
    cmd: |
      umask {{ my_user.umask }}
      pathmunge() { PATH=$PATH:$1 ; }
      [ -f {{ my_user.home }}/.profile.d/golang.sh ] && . {{ my_user.home }}/.profile.d/golang.sh
      # Install globally (tools that go to GOPATH/bin)
      go install {{ item }}@latest
  with_items: "{{ go_packages }}"
  when:
    - has_go.rc == 0

# Install golangci-lint latest version to GOPATH.
# NOTE: Can't go install; see https://golangci-lint.run/usage/install/#install-from-source
- name: Installing golangci-lint To GOPATH
  shell:
    chdir: "{{ my_user.home }}"
    cmd: |
      umask {{ my_user.umask }}
      pathmunge() { PATH=$PATH:$1 ; }
      [ -f {{ my_user.home }}/.profile.d/golang.sh ] && . {{ my_user.home }}/.profile.d/golang.sh
      curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
  when:
    - has_go.rc == 0
