---
# Development environment setup

# Linux
- block:
    - import_tasks: apt.yml
    - import_tasks: rpm.yml
  become: true
  become_user: "root"
  when:
    - ansible_facts.system == "Linux"
    - my_facts.has_become_root

- block:
    - import_tasks: go.yml
    - import_tasks: nodejs.yml
    - import_tasks: python.yml
  become: true
  become_user: "{{ my_user.username }}"
  when:
    - ansible_facts.system == "Linux"
    - my_facts.has_become_my_user

# Windows
- block:
    - import_tasks: windows_choco.yml
  # WARN: 'become' to user itself is required to allow credential delegation;
  # user is expected to be an Administrator.
  become: true
  become_user: "{{ my_user.domain_username }}"
  when:
    - ansible_facts.os_family == "Windows"
    - my_user.is_administrator
