---
# Development environment setup

# Linux
- block:
    - import_tasks: apt.yml
  become: true
  become_user: "root"
  when:
    - ansible_facts.os_family == "Debian"
    - my_facts.has_become_root

- block:
    - import_tasks: go.yml
    - import_tasks: nodejs.yml
    - import_tasks: python.yml
  become: true
  become_user: "{{ my_user.username }}"
  when:
    - ansible_facts.os_family == "Debian"
    - my_facts.has_become_my_user
