---
# Setup Python development environment

- name: Detecting python3
  command: python3 --version
  failed_when: false
  changed_when: false
  register: has_python3

- name: Creating ~/.local/python Virtual Environment
  shell:
    chdir: "{{ my_user.home }}"
    cmd: |
      umask {{ my_user.umask }}
      python3 -m venv .local/python
    creates: "{{ my_user.home }}/.local/python"
  register: has_venv
  when:
    - has_python3.rc == 0

- name: Installing Python Packages
  shell:
    chdir: "{{ my_user.home }}"
    cmd: |
      umask {{ my_user.umask }}
      .local/python/bin/pip install {{ item }}
  with_items: "{{ python_packages }}"
  when:
    - has_python3.rc == 0
    - has_venv.rc == 0
