---

# Linux (and WSL) play
# NOTE: wsl_pre_tasks.yml detects if this is WSL system AND if so it attempts
# to configure winrm client-certificate authorized connection. If you don't
# want that add --skip-tags winrm.
- name: Linux
  hosts: linux

  pre_tasks:
    - { import_tasks: tasks/linux_pre_tasks.yml, tags: always }
    - { import_tasks: tasks/wsl_pre_tasks.yml, tags: always }

  roles:
    - { role: base, tags: [base, linux] } 
    - { role: user, tags: [user, linux] }
    - { role: dev, tags: [dev, linux] }

# Windows play
- name: Windows
  hosts: windows

  pre_tasks:
    - { import_tasks: tasks/win_pre_tasks.yml, tags: always }

  roles:
    - { role: base, tags: [base, windows] }
    - { role: user, tags: [user, windows] }
    - { role: dev, tags: [dev, windows] }
