---
# APT repositories and packages variables

apt_repositories:
  # Docker
  - name: "docker"
    key_id: "8D81803C0EBFCD88"
    sources:
      - "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  # Kubernetes
  - name: "kubernetes"
    key_id: "B53DC80D13EDEF05"
    # NOTE: There is no newer APT dist than yakkety
    sources:
      - "deb http://apt.kubernetes.io/ kubernetes-yakkety main"

apt_packages:
  - containerd.io           # containerd from Docker CE APT repository
  - kubeadm
  - kubelet
  - kubectl
