---
# Install Calico

# TODO: If tigera-operator is not installed install it

- name: Installing calicoctl
  get_url: 
    url: https://github.com/projectcalico/calico/releases/download/v3.23.3/calicoctl-linux-amd64
    dest: /usr/local/bin/calicoctl
    owner: root
    group: root
    mode: 755
  when:
    - ansible_architecture in ("x86_64",)
