---
# Disable swap
# NOTE: Kubernetes require swap to be permanently disabled

- name: Disabling Swap
  shell: |
    swapoff -a

- name: Disabling Swap Paritions And Files
  replace:
    path: /etc/fstab
    regexp: "^([^#].*?\\sswap\\s+sw\\s+.*)$"
    replace: "# \\1"
