---
# Setup Kernel Modules

- name: Enabling Kernel Modules
  copy:
    src: "{{ role_path }}/files/modules-load.d/kubernetes.conf"
    dest: "/etc/modules-load.d/kubernetes.conf"
    owner: root
    group: root
    mode: 644
    force: true
  register: out

- name: Updating initramfs
  command: /usr/sbin/update-initramfs -u -k all 
  when: 
    - out.changed

- name: Loading Kernel Modules
  shell: |
    while read mod; do
      case "$mod" in \#*) continue ;; esac
      /usr/sbin/modprobe "$mod"
    done < /etc/modules-load.d/kubernetes.conf
  # NOTE: Not when: as it does not hurt to probe already inserted modules
