---
# Check WinRM connection and set can_winrm and has_pywinrm my_facts.
# See: /tasks/post_wsl_winrm.yml

- name: "Checking If Ansible Can WinRM To {{ my_facts.wsl_host_ip }}"
  xtest_winrm:
    hostname: "{{ my_facts.wsl_host_hostname }}"
    winrm_transport: certificate
    winrm_cert_pem: "{{ my_user.home }}/.ansible/winrm/localclient.crt"
    winrm_cert_key_pem: "{{ my_user.home }}/.ansible/winrm/localclient.key"
    winrm_server_cert_validation: ignore
  register: out
  when:
    - my_facts.is_wsl
    - my_facts.has_my_user
  tags: localwinrm
- set_fact:
    my_facts: >
      {{
        my_facts | xcombine({
          "can_winrm": out.can_winrm,
          "has_pywinrm": out.has_pywinrm
        })
      }}
  when:
    - my_facts.wsl_host_ip
    - my_facts.is_wsl
    - my_facts.has_my_user
  tags: localwinrm
