---
# Windows-only additional fact gathering and checks.

# NOTE: win_chocolatey_facts takes too long; this is much faster
- name: Checking If Chocolatey Is Installed
  win_shell: choco --version
  register: out
  changed_when: false
  failed_when: false
- set_fact:
    my_facts: >
      {{ my_facts | xcombine({
        "has_choco": out.rc == 0
      }) }}

- name: Gathering Chocolatey Source Location
  set_fact:
    my_facts: >
      {{ my_facts | xcombine({
        "win_choco_source": my_facts.wsl_unc_home_dir + "\ops\choco" if my_facts.is_wsl else my_facts.choco_source
      }) }}
