---
# Linux-only additional fact gathering and checks.

- name: "Gathering Package Facts"
  package_facts:
    manager: auto

# NOTE: service_mgr fact fails on WSL (shows systemd but in fact its not).
- name: "Checking if systemd is PID1"
  command:
    cmd: "/bin/systemctl"
  register: out
  failed_when: false
  changed_when: false
- set_fact:
    my_facts: >
      {{ my_facts | xcombine({
        "has_systemd": false if out.rc != 0 else true
      }) }}
