---
# Setup Bitwarden CLI on control node.
# NOTE: All tasks here are delegated to localhost as they should run only on
# control node.
#
# As of now this requires second run after login and unlock with exported
# BW_SESSION.
# TODO: Maybe automate that part?

# NOTE: This requires root on control node
- name: "Installing Bitwarden CLI"
  unarchive:
    src: "https://vault.bitwarden.com/download/?app=cli&platform=linux"
    dest: "/usr/local/bin"
    remote_src: true
    owner: root
    group: root
    mode: 0755
  become: true
  become_user: root
  delegate_to: localhost
  when:
    - "hostvars['localhost'].ansible_architecture in ('x86_64', )"
    - my_control_node_facts.has_become_root

- name: "Checking Bitwarden CLI Status"
  set_fact:
    my_control_node_facts: >
      {{ my_control_node_facts | xcombine({
        "has_bitwarden": lookup("bitwarden") == "unlocked",
      }) }}

- block:
  - fail:
      msg: "WARNING: Bitwarden CLI on control node is not available or unlocked!"
    ignore_errors: true
  - pause:
      seconds: 5

  when:
    - not my_control_node_facts.has_bitwarden
