---
# Linux-only additional fact gathering and checks.

- name: "Gathering Package Facts"
  package_facts:
    manager: auto

# NOTE: service_mgr fact fails on WSL (shows systemd but in fact its not).
- include_role:
    name: _common
    tasks_from: checks/check_has
  vars:
    has_command:
      - { command: "systemctl", fact: "has_systemd" }
