---
# LAN presence check

- block:
    - name: Checking If In LAN
      command: ping -c 1 -w 1 {{ my_lan.router }}
      register: out
      failed_when: false
      changed_when: false
    - set_fact:
        my_facts: >
          {{ my_facts | xcombine({
            "has_lan": out.rc == 0
          }) }}
  when:
    - ansible_facts.system == "Linux"

- block:
    - name: Checking If In LAN
      win_command: ping -c 1 -w 1 {{ my_lan.router }}
      register: out
      failed_when: false
      changed_when: false
    - set_fact:
        my_facts: >
          {{ my_facts | xcombine({
            "has_lan": out.rc == 0
          }) }}
  when:
    - ansible_facts.os_family == "Windows"
