#!/usr/bin/zsh
# ~/.zsh/prompt/cwdlst - output last component of current working directory

# Usage: cwdlast

cwdlast () {
    local cwd=${PWD/#$HOME/\~}
    [ -L $HOME ] && cwd=${cwd/$(readlink -m $HOME)/\~}

    cwd=${cwd/*\//}
    [ -z $cwd ] && cwd=/
    echo $cwd
}

cwdlast $@
