---
# Clone and update dotfiles.

# NOTE Not using built-in `git` as this is cloned into a homedir which already
# exists.
- name: Cloning dotfiles repository
  shell:
    chdir: "{{ my_user.home }}"
    creates: "{{ my_user.home }}/.dfgit"
    cmd: |
      umask {{ my_user.umask }}
      git init --separate-git-dir .dfgit
      git --git-dir=.dfgit remote add -f -m main origin {{ dotfiles_repo }}
      git --git-dir=.dfgit reset --hard origin/main
      git --git-dir=.dfgit checkout main
      [ -f .git ] && rm -rf .git
  register: out

- name: Update dotfiles
  shell:
    chdir: "{{ my_user.home }}"
    # TODO Check if pull can be done...
    # https://stackoverflow.com/questions/24504400/whats-the-correct-way-to-check-if-its-possible-to-perform-a-fast-forward-merge
    cmd: |
      umask {{ my_user.umask }}
      git --git-dir=.dfgit pull
  # Do not run if dotfiles were just cloned
  when:
    - not out.changed
