---
# User setup

# Linux (and WSL)
- block:
    - import_tasks: apt.yml
    - import_tasks: shell.yml
  become: yes
  become_user: "root"
  when:
    - ansible_facts.os_family == "Debian"
    - my_facts.can_become_root

- block:
    - import_tasks: dotfiles.yml
    - import_tasks: userdirs.yml
    - import_tasks: secrets.yml
    - import_tasks: licenses.yml
    - import_tasks: nvim.yml
  become: yes
  become_user: "{{ my_user.username }}"
  when:
    - ansible_facts.os_family == "Debian"
    - my_facts.can_become_user


# Windows
- block:
    - import_tasks: win_env.yml
    - import_tasks: win_registry.yml
  when:
    - ansible_facts.os_family == "Windows"
    #- my_facts.can_become_user

