---
# Install and/or update Neovim packs.

- name: Installing Neovim packs
  shell:
    cmd: |
      NVIM_SITE_PACK={{ my_user.home }}/.local/share/nvim/site/pack
      mkdir -p $NVIM_SITE_PACK
      git clone {{ item.repo }} $NVIM_SITE_PACK/plugins/start/{{ item.name }}
    creates: "{{ my_user.home }}/.local/share/nvim/site/pack/{{ item.group }}/start/{{ item.name }}"
  with_items: "{{ nvim_packs }}"
  loop_control:
    label: "clone {{ item.name }}"

- name: Updating Neovim packs
  shell:
    cmd: |
      NVIM_SITE_PACK={{ my_user.home }}/.local/share/nvim/site/pack
      git -C $NVIM_SITE_PACK/{{ item.group }}/start/{{ item.name }} pull
  with_items: "{{ nvim_packs }}"
  loop_control:
    label: "update {{ item.name }}"
