---
# Install various secrets (SSH, GPG keys and PEMs) stored in LastPass.
# NOTE lpass CLI asks interacively for a password if vault was unlocked and
# agent expired. To avoid that we set 'LPASS_ASKPASS=/bin/false'.

- name: Checking LastPass status
  command: >
    lpass status
  environment:
    LPASS_ASKPASS: /bin/false
  register: lpass
  # Never failed nor changed
  failed_when: false
  changed_when: false

- name: Installing SSH keys from LastPass
  shell:
    chdir: "{{ my_user.home }}"
    cmd: |
      lpass show --sync now "{{ item.name }}" --field="Private Key" > .ssh/keys/{{ item.file }}
      lpass show "{{ item.name }}" --field="Public Key" > .ssh/keys/{{ item.file }}.pub
      chmod 0600 .ssh/keys/{{ item.file }}
  environment:
    LPASS_ASKPASS: /bin/false
  # NOTE DO NOT use 'creates:' here to allow ssh key updates
  with_items: "{{ ssh_keys }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - lpass.rc == 0

# TODO Do GPG later
# TODO First check if identity exists and if does skip this
- name: Installing GnuPG keys from LastPass
  shell:
    chdir: "{{ my_user.home }}"
    cmd: |
      PASSPHRASE=$(lpass show --sync now "{{ item.name }}" --field="Passphrase")

      # Import stuff


      # Trust key
      #echo -e "5\ny\n" | gpg --command-fd 0 --edit-key {{ item.identity }} trust
  environment:
    LPASS_ASKPASS: /bin/false
  with_items: "{{ gpg_certs }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - lpass.rc == 0

- name: Installing IRC certificates from LastPass
  shell:
    chdir: "{{ my_user.home }}"
    cmd: |
      lpass show --sync now "{{ item.name }}" --notes > .config/weechat/certs/{{ item.file }}
      chmod 0600 .config/weechat/certs/{{ item.file }}
  environment:
    LPASS_ASKPASS: "/bin/false"
  # NOTE DO NOT use 'creates:' here to allow irc certificate updates
  with_items: "{{ irc_certs }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - lpass.rc == 0
