---
# Install various secrets (SSH, GPG keys and PEMs) stored in Bitwarden.
# Bitwarden CLI has to be installed.

# TODO This currently works only when run locally with BW_SESSION exported,
# probably need to unlock bitwarden on target host and instead of exporting
# BW_SESSION pass it to master?

- name: Checking Bitwarden status
  shell: |
    bw status | jq -r .status 
  register: out
  # Never failed nor changed
  failed_when: false
  changed_when: false

# SSH keys are expected to be named "SSH keyfile" and have two attachments of
# names keyfile (private key) and keyfile.pub (public key).
# NOTE ~/.ssh/keys is expected to exist (userdirs.yml)
- name: Fetching SSH keys
  shell: |
    for F in "{{ item }}" "{{ item }}.pub" ; do
      ID=$(bw get item "SSH {{ item }}" | jq -r ".id")
      ATTACH_ID=$(bw get item $ID | jq -r ".attachments[] | select((.fileName == \"$F\")).id")
      bw get attachment $ATTACH_ID --itemid $ID --output {{ my_user.home }}/.ssh/keys/$F
    done
    chmod $((666 - {{ my_user.umask }})) {{ my_user.home }}/.ssh/keys/{{ item }}.pub
  with_items: "{{ ssh_keys }}"
  when:
    - out.stdout == "unlocked"

# IRC certificates are expected to be named "IRC server" and have single
# attachment of name server_user.pem.
# NOTE ~/.config/weechat/cets is expected to exist (userdirs.yml)
- name: Fetching IRC client certificates
  shell: |
    ID=$(bw get item "IRC {{ item.server }}" | jq -r ".id")
    ATTACH_ID=$(bw get item $ID | jq -r ".attachments[] | select((.fileName == \"{{ item.server }}_{{ item.user }}.pem\")).id")
    bw get attachment $ATTACH_ID --itemid $ID --output {{ my_user.home }}/.config/weechat/certs/{{ item.server }}_{{ item.user }}.pem
  with_items: "{{ irc_certs }}"
  when:
    - out.stdout == "unlocked"

# TODO GPG keys
