---
# Install various secrets (SSH, GPG keys and PEMs) stored in Bitwarden.
# Bitwarden CLI has to be installed.

- name: Checking Bitwarden status
  shell: |
    echo bw
  register: bw
  # Never failed nor changed
  failed_when: false
  changed_when: false
