---
# Install various secrets (SSH, GPG keys and PEMs) stored in Bitwarden

# TODO: This currently works only when run locally with BW_SESSION exported,
# probably need to unlock bitwarden on target host and instead of exporting
# BW_SESSION pass it to master?

- name: Checking Bitwarden status
  shell: |
    bw status | jq -r .status 
  register: out
  # Never failed nor changed
  failed_when: false
  changed_when: false

# SSH keys are expected to be named "SSH keyfile" and have two attachments of
# names keyfile (private key) and keyfile.pub (public key).
# NOTE ~/.ssh/keys is expected to exist (userdirs.yml)
- name: Fetching SSH keys
  shell: |
    for F in "{{ item }}" "{{ item }}.pub" ; do
      ID=$(bw get item "SSH {{ item }}" | jq -r ".id")
      ATTACH_ID=$(bw get item $ID | jq -r ".attachments[] | select((.fileName == \"$F\")).id")
      bw get attachment $ATTACH_ID --itemid $ID --output {{ my_user.home }}/.ssh/keys/$F
    done
    chmod $((666 - {{ my_user.umask }})) {{ my_user.home }}/.ssh/keys/{{ item }}.pub
  with_items: "{{ ssh_keys }}"
  when:
    - out.stdout == "unlocked"

# GPG keys are expected to be named "GPG identity" and have two attachments
# identity.priv.asc with main private key, identity.sub_priv.asc with private
# subkeys and custom field "Passphrase" (self-explanatory).
- name: Fetching GPG keys
  shell: |
    ITEM=$(bw get item "GPG {{ item }}")
    ID=$(echo $ITEM | jq -r ".id")
    PASSPHRASE=$(echo $ITEM | jq -r ".fields[] | select((.name==\"Passphrase\")).value")
    TEMPDIR=$(mktemp -d) 
    for A in "{{ item }}.priv.asc" "{{ item }}.sub_priv.asc" ; do
      ATTACH_ID=$(bw get item $ID | jq -r ".attachments[] | select((.fileName == \"$A\")).id")
      bw get attachment $ATTACH_ID --itemid $ID --output $TEMPDIR/$A
      gpg --batch --yes --pinentry-mode=loopback --passphrase=$PASSPHRASE --import $TEMPDIR/$A
    done
    # NOTE Ansible breaks fd 0; so need to use command file
    echo "5\ny\n" > $TEMPDIR/command
    gpg --command-file $TEMPDIR/command --expert --edit-key {{ item }} trust
    rm -rf $TEMPDIR
  with_items: "{{ gpg_keys }}"
  when:
    - out.stdout == "unlocked"
    
# IRC certificates are expected to be named "IRC server" and have single
# attachment of name server_user.pem.
# NOTE ~/.config/weechat/cets is expected to exist (userdirs.yml)
- name: Fetching IRC client certificates
  shell: |
    ID=$(bw get item "IRC {{ item.server }}" | jq -r ".id")
    ATTACH_ID=$(bw get item $ID | jq -r ".attachments[] | select((.fileName == \"{{ item.server }}_{{ item.user }}.pem\")).id")
    bw get attachment $ATTACH_ID --itemid $ID --output {{ my_user.home }}/.config/weechat/certs/{{ item.server }}_{{ item.user }}.pem
  with_items: "{{ irc_certs }}"
  when:
    - out.stdout == "unlocked"
