---
# Create common user directories; see ~/.config/user-dirs.dirs for details

- name: Creating ~ directories
  file:
    path: "{{ my_user.home }}/{{ item }}"
    state: directory
  with_items:
    # XDG user directories
    - "desk"                  # XDG_DESKTOP_DIR
    - "docs"                  # XDG_DOCUMENTS_DIR
    - "downl"                 # XDG_DOWNLOAD_DIR
    - "pics"                  # XDG_PICTURES_DIR
    - "music"                 # XDG_MUSIC_DIR
    - "videos"                # XDG_VIDEOS_DIR
    - "pub"                   # XDG_PUBLICSHARE_DIR
    # Non-XDG (but I still have some of them in user-dirs.dirs)
    - "bak"                   # backups (XDG_BACKUP_DIR)
    - "mail"                  # mail (XDG_MAIL_DIR)
    - "src"                   # source code (XDG_SRC_DIR)
    - "public_html"           # public_html (XDG_PUBLICHTML_DIR)
    - "tmp"                   # temporary files
    # Sub-directories
    - "downl/arch"

- name: Creating SSH keys directory
  file:
    path: "{{ my_user.home }}/.ssh/keys"
    mode: "0700"
    state: directory

- name: Creating IRC certs directory
  file:
    path: "{{ my_user.home }}/.config/weechat/certs"
    mode: "0700"
    state: directory

# On WSL certain directories have to be on native filesystem
- name: Creating WSL native directories
  file:
    path: "{{ item.src }}"
    mode: "{{ item.mode }}"
    state: directory
  loop_control:
    label: "{{ item.src }}"
  with_items: "{{ wsl_native_dirs }}"
  when:
    - my_facts.is_wsl
    - my_facts.home_filesystem == "drvfs"

- name: Symlinking WSL native directories
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    # NOTE This will delete (unlink) the original file if its not a symlink and
    # create the symlink
    force: true
  loop_control:
    label: "{{ item.dest }}"
  with_items: "{{ wsl_native_dirs }}"
  when:
    - my_facts.is_wsl
    - my_facts.home_filesystem == "drvfs"
