---
# Setup Windows UI aspects

# Install system cursors
# NOTE: This checks if SCHEME_NAME is installed in registry and if not it
# attempts to install it from INF. Check is very opinionated and works with MY
# own cursor scheme INFs.
- name: Installing Windows cursors
  win_shell: |
    $changed = 0
    switch -regex -file "{{ my_user.home }}\\.local\\share\\icons\\{{ item }}" {
      '^\s*SCHEME_NAME\s*=\s*"?([^"]*)"?$' { $scheme = $matches[1] }
    }
    if (-not(Get-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Control Panel\\Cursors\\Schemes" $scheme -ErrorAction SilentlyContinue)) {
      rundll32.exe advpack.dll,LaunchINFSectionEx "{{ my_user.home }}\\.local\\share\\icons\\{{ item }},,,4"
      $changed = 1
    }
    Write-Host $changed
  register: result
  changed_when: result.stdout | int > 0
  with_items:
    - aero_black\cursors\install.inf
    - aero_black\cursors\install_l.inf
    - aero_black\cursors\install_xl.inf
  when:
    - my_facts.is_administrator
    - my_facts.has_dotfiles

# Make window under mouse focused but not raised with delay of 200ms
# NOTE: Can't use SystemParamsInfo from user32.dll through WinRM, also can't
# use win_regedit as this requires bit flipping (lol).
# TODO: This requires sign-out/sign-in.
- name: Setting Windows focus follows mouse (X11 style)
  win_shell: |
    $changed = 0
    # Flip 1st bit of UserPreferencesMask (ActiveWindowTracking)
    $pref = Get-ItemProperty "HKCU:\Control Panel\Desktop" "UserPreferencesMask"
    if (-not($pref.UserPreferencesMask[0] -band 1)) {
      $pref.UserPreferencesMask[0] = ($pref.UserPreferencesMask[0] -bxor 1)
      Set-ItemProperty "HKCU:\Control Panel\Desktop" "UserPreferencesMask" $pref.UserPreferencesMask
      $changed += 1
    }
    # Set timeout to 200ms
    if ((Get-ItemProperty "HKCU:\Control Panel\Desktop" "ActiveWndTrkTimeout").ActiveWndTrkTimeout -ne 200) {
      Set-ItemProperty "HKCU:\Control Panel\Desktop" "ActiveWndTrkTimeout" 200
      $changed += 1
    }
    # ?
    if ((Get-ItemProperty "HKCU:\Control Panel\Mouse" "ActiveWindowTracking").ActiveWindowTracking -ne 1) {
      Set-ItemProperty "HKCU:\Control Panel\Mouse" "ActiveWindowTracking" 1
      $changed += 1
    }
    Write-Host $changed
  register: result
  changed_when: result.stdout | int > 0

- name: Installing Windows user fonts
  win_shell: |
    $changed = 0
    $fonts = Get-ChildItem -Path "C:\\Users\\blami\\.local\\share\\fonts" -Recurse -Include *.ttf,*.otf
    $shell = New-Object -ComObject shell.application
    foreach ($f in $fonts) {
      # Figure out font name
      $folder = $shell.Namespace($f.DirectoryName)
      $item = $folder.Items().Item($f.Name)
      $name = $folder.GetDetailsOf($item, 21)
      switch ($f.Extension) {
        ".ttf" { $name = "$name (TrueType)" }
        ".otf" { $name = "$name (OpenType)" }
      }
      $dest = "$($Env:LocalAppData)\\Microsoft\\Windows\\Fonts\\$($f.Name)"
      $reg = "HKCU:\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Fonts"
      if ((Test-Path $dest) -and (Get-ItemProperty `
        -Name $name `
        -Path $reg `
        -ErrorAction SilentlyContinue)) {
        continue
      }
      Copy-Item -Path $f.FullName -Destination $dest -Force
      if (-not(Test-Path $reg)) { New-Item -Path $reg -Force | Out-Null }
      New-ItemProperty `
        -Name $name `
        -Path $reg `
        -Value $dest `
        -PropertyType string -Force | Out-Null
      $changed += 1
    }
    Write-Host $changed
  register: result
  changed_when: result.stdout | int > 0
  when:
    - my_facts.has_dotfiles
