---
# Additional APT repositories and packages to install

apt_repositories:
  # Neovim
  - name: "ppa_neovim"
    key_id: "55F96FCF8231B6DD"
    sources:
      - "deb http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu {{ ansible_distribution_release }} main"
  # Git
  - name: "ppa_gitcore-git"
    key_id: "A1715D88E1DF1F24"
    sources:
      - "deb http://ppa.launchpad.net/git-core/ppa/ubuntu {{ ansible_distribution_release }} main"
  # Ansible
  #- name: "ppa_ansible"
  #  key_id: "6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367"
  #  sources:
  #    - "deb https://ppa.launchpadcontent.net/ansible/ansible/ubuntu {{ ansible_distribution_release }} main"

apt_packages:
  #- snapd                    # WARN: DO NOT add snapd here
  - acl                       # manage filesystem access lists
  - apt-transport-https       # https support for APT
  - bpfcc-tools               # BPF compiler collection
  - bpftrace                  # BPF tracing analyzer
  - cpuid
  - cryptsetup-bin
  - curl
  - dnsutils                  # dig
  - dosfstools
  - equivs
  - fakeroot                  # simulate running as root
  - gawk
  - gdisk
  - git
  - git-lfs
  - gnupg
  - gzip
  - htop
  - icdiff                    # side by side diff
  - ipcalc                    # IP address/mask/subnet arithmetics calculator
  - jq                        # JSON parser and query language
  - less
  - lftp
  - lm-sensors
  - locales
  - logrotate
  - lsof                      # list open files
  - ltrace
  - m4                        # macro processor
  - make
  - mosh                      # mobile shell
  - mtr                       # traceroute & ping
  - neovim
  - net-tools                 # netstat & co.
  - netperf                   # network speed meter
  - nmap
  - openssh-client
  - p7zip
  - powertop                  # power management utility
  - procps                    # /proc utilities
  - psmisc
  - pv                        # progressbar
  - pwgen
  - python3
  - python3-winrm             # required to Ansible-remote to Windows
  - rclone
  - rsnapshot
  - rsync
  - shellcheck                # lint shell scripts
  - socat
  - sqlite3
  - squashfs-tools
  - sshfs                     # mount filesystems over ssh and fuse
  - strace
  - stress-ng                 # stress test system (load)
  - telnet
  - tmux
  - tshark                    # network traffic capture and analysis
  - unzip
  - unzip
  - wdiff
  - wget
  - xdelta3
  - xz-utils
  - zip
  - zsh

apt_packages_unwanted:
  - command-not-found
  - command-not-found-data
  - motd-news-config
  - popularity-contest
  - show-motd
  - ufw                       # Ubuntu firewall?
  - update-motd
