---
# Development environment setup for C, C++, Assembly, Go, Python, Javascript
# and possibly other languages.

# Linux (and WSL)
- block:
    - import_tasks: apt.yml
    - import_tasks: fakeroot.yml
  become: true
  become_user: "root"
  when:
    - ansible_facts.os_family == "Debian"
    - my_facts.can_become_root

- block:
    - import_tasks: go.yml
    - import_tasks: nodejs.yml
    - import_tasks: python.yml
  become: true
  become_user: "{{ my_user.username }}"
  when:
    - ansible_facts.os_family == "Debian"
    - my_facts.can_become_user


# Windows
- block:
    - import_tasks: win_msvs.yml
  when:
    - ansible_facts.os_family == "Windows"
    #- my_facts.can_become_user

