---
# Install Node.js packages.

# TODO Check if node is present; otherwise skip all here
# TODO Make sure we look for node not only in default PATH? maybe subshell to
# my_user.shell?


- name: Setting up Node.js (.npmrc)
  shell:
    chdir: "{{ my_user.home }}"
    # NOTE Do not use 'creates:' to always revert changed prefix to ~/.node
    #creates: "{{ my_user.home }}/.npmrc"
    cmd: |
      umask {{ my_user.umask }}
      npm config set prefix ~/.node

- name: Installing Node.js packages
  shell:
    chdir: "{{ my_user.home }}"
    cmd: |
      umask {{ my_user.umask }}
      npm install -g {{ item }}
  with_items: "{{ nodejs_packages }}"
