---
# Configure APT and install/remove basic packages
# TODO: Old kernel autoremoval

- name: Disabling APT Recommendations
  copy:
    src: "{{ role_path }}/files/apt.conf.d/99no-recommends"
    dest: "/etc/apt/apt.conf.d/99no-recommends"
    owner: root
    group: root
    mode: 644
    force: true
  when:
    - ansible_facts.os_family == "Debian"

- name: Removing Default APT Sources
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/apt/sources.list"
    - "/etc/apt/sources.list.d/debian.sources"
  when:
    - ansible_facts.os_family == "Debian"

- name: Adding Release Priorities
  copy:
    src: "{{ role_path }}/files/apt.preferences.d/10release-priority"
    dest: "/etc/apt/preferences.d/10release-priority"
    owner: root
    group: root
    mode: 644
    force: true
  when:
    - ansible_facts.os_family == "Debian"

- include_role:
    name: common
    tasks_from: apt_sources

- name: Upgrading APT Packages
  apt:
    upgrade: "safe"
    autoremove: true
  when:
    - ansible_facts.os_family == "Debian"

- include_role:
    name: common
    tasks_from: apt_packages
