---
# Install Bitwarden CLI

- name: Detecting Bitwarden CLI
  stat:
    path: /usr/local/bin/bw
  register: out_bw_bin
  when:
    # NOTE: Bitwarden CLI native binary is only available for amd64
    - ansible_architecture in ("x86_64",)

- name: Downloading Bitwarden CLI
  get_url: 
    url: https://vault.bitwarden.com/download/?app=cli&platform=linux
    # NOTE: Keep .zip so changed=true can be used as trigger to upgrade
    dest: /var/cache/ansible/bw.zip
  register: out_bw_download
  when:
    - ansible_architecture in ("x86_64",)

- name: Installing Bitwarden CLI
  shell: |
    unzip -o /var/cache/ansible/bw.zip bw -d /usr/local/bin
    chown root:root /usr/local/bin/bw
    chmod +x /usr/local/bin/bw
  when:
    - ansible_architecture in ("x86_64",)
    # NOTE: Only install if download changed or binary is missing
    - out_bw_download.changed or not out_bw_bin.stat.exists
