---
# Configure APT and install OS base packages

- name: "Disabling DEB Package Recommendations"
  copy:
    src: "{{ role_path }}/files/apt.conf.d/99no-recommends"
    dest: "/etc/apt/apt.conf.d/99no-recommends"
    owner: root
    group: root
    mode: 644
    force: true

- name: "Removing Default DEB Package Sources"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/apt/sources.list"
    - "/etc/apt/sources.list.d/debian.sources"

- name: "Adding Release Priorities"
  copy:
    src: "{{ role_path }}/files/apt.preferences.d/10release-priority"
    dest: "/etc/apt/preferences.d/10release-priority"
    owner: root
    group: root
    mode: 644
    force: true

# Add sources
- include_role:
    name: _common
    tasks_from: deb_sources

- name: "Removing Unwanted DEB Packages"
  apt:
    pkg: "{{ deb_packages_remove }}"
    purge: true
    state: absent

- name: "Upgrading DEB Packages"
  apt:
    upgrade: "safe"
    autoremove: true
  when:
    - ansible_facts.os_family == "Debian"

# Install packages
- include_role:
    name: _common
    tasks_from: deb_packages
