---
# Create additional OS-level directories

- name: Removing /media
  file:
    path: /media
    state: absent

# Ansible cache directory to hold various artifacts
- name: Creating /var/cache/ansible
  file:
    path: /var/cache/ansible
    mode: 755
    owner: root
    group: root
    state: directory
