---
# Setup locales

# Debian
- block:
  - name: "Installing /etc/locale.gen"
    copy:
      src: "{{ role_path }}/files/locale.gen"
      dest: "/etc/locale.gen"
      owner: root
      group: root
      mode: 0644
      force: true
    register: out

  - name: "Regenerating Locales"
    command: "/usr/sbin/locale-gen"
    when:
      - out.changed

  when: ansible_facts.os_family == "Debian"

# RedHat
#- block:
  # TODO:

#  when: ansible_facts.os_family == "RedHat"
