---
# Regenerate locales

- name: Installing /etc/locale.gen
  copy:
    src: "{{ role_path }}/files/locale.gen"
    dest: "/etc/locale.gen"
    owner: root
    group: root
    mode: 644
    force: true
  when:
    - ansible_facts.os_family == "Debian"
  register: out

- name: Regenerating Locales
  command: "/usr/sbin/locale-gen"
  when:
    - ansible_facts.os_family == "Debian"
    - out.changed

# TODO: localectl when systemd
#- name
