---
# Base OS setup

# Linux
- block:
    - import_tasks: wsl.yml             # run this first as it may restart WSL
    - import_tasks: dirs.yml            # create additional directories
    - import_tasks: user.yml
    - import_tasks: sudoers.yml
    - import_tasks: netplan.yml
    - import_tasks: snap.yml            # disable snap
    - import_tasks: apport.yml          # disable Apport
    - import_tasks: apt.yml
    - import_tasks: bitwarden.yml       # install Bitwarden CLI
  become: true
  become_user: "root"
  when:
    - ansible_facts.os_family == "Debian"
    - my_facts.has_become_root

# Windows
- block:
    - import_tasks: windows_onedrive.yml
    - import_tasks: windows_choco.yml
  become: true
  become_user: "System"
  become_method: "runas"
  when:
    - ansible_facts.os_family == "Windows"
    - my_facts.has_become_system
