---
# Setup base operating system

# Linux
- block:
    - import_tasks: apt.yml               # setup APT and install essentials
    - import_tasks: locale.yml
    - import_tasks: ntp.yml
    - import_tasks: dirs.yml              # OS-level directories
    - import_tasks: user.yml              # create and/or configure user
    - import_tasks: sudoers.yml
    - import_tasks: nvim.yml              # install Neovim (upstream)
    - import_tasks: bitwarden.yml         # install Bitwarden CLI
    - import_tasks: systemd.yml           # configure systemd
    #- import_tasks: grub.yml
    - import_tasks: wsl.yml               # configure WSL (might restart WSL)
  become: true
  become_user: "root"
  when:
    - ansible_facts.os_family == "Debian"
    - my_facts.has_become_root

# Windows
- block:
    - import_tasks: windows_choco.yml     # install essentials
    - import_tasks: windows_debloat.yml   # de-bloat Windows
    - import_tasks: windows_ntp.yml
    - import_tasks: windows_network.yml
    - import_tasks: windows_power.yml
  # WARN: 'become' to user itself is required to allow credential delegation;
  # user is expected to be an Administrator.
  become: true
  become_user: "{{ my_user.domain_username }}"
  when:
    - ansible_facts.os_family == "Windows"
    - my_user.is_administrator
