---
# Configure NTP servers

# TODO: only when file actually exists...
- name: Configuring NTP Servers
  replace:
    path: /etc/systemd/timesyncd.conf
    regexp: '^#?((.*)NTP)=.*$'
    replace: '\1={{ ntp_server }}'
  register: out

- name: Restarting timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted
  when:
    - my_facts.has_systemd
    - out.changed
