---
# Configure sudo

# NOTE: On non-Debian systems is sometimes wheel used instead of sudo; to use
# my /etc/sudoers file sudo is required.
- name: "Adding sudo group"
  group:
    name: sudo
    system: true
    state: present

- name: "Installing sudo files"
  template:
    src: "{{ role_path }}/files/{{ item }}.j2"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: 0644
    force: true
  with_items:
    - sudoers
    - sudoers.d/99-sudo_defaults
    - sudoers.d/20-ansible

- name: "Removing root Password"
  user:
    name: root
    password: ""
    state: present
  when:
    - my_user.is_local
