---
# Create user account

# In case user already exists this will just update fields.
- name: Setting Up User {{ my_user.username }}
  user:
    name: "{{ my_user.username }}"
    comment: "{{ my_user.gecos }}"
    # NOTE: DO NOT set shell as it might not be installed yet; there's task in
    # user/shell to do that.
    #shell: {{ my_user.shell }}
    # NOTE: Use system home directory see update command bellow
    move_home: false
  register: out

# NOTE: If user was created force password change on next login
- name: Forcing User {{ my_user.username }} To Change Password
  command: chage -d0 {{ my_user.username }}
  when:
    - not my_facts.has_my_user
    - out.changed

- name: Adding User {{ my_user.username }} To Groups
  user:
    name: "{{ my_user.username }}"
    groups: "{{ my_user.groups }}"
    append: true
  with_items: "{{ my_user.groups }}"
  when:
    - item in ansible_facts.getent_group

- name: Refreshing User Facts
  set_fact:
    my_user: >
      {{ my_user | xcombine({
        "home": out['home']
      }) }}
    # NOTE: This is not 100% correct but will work in most cases
    my_facts: >
      {{ my_facts | xcombine({
        "has_my_user": true,
        "has_become_my_user": true
      }) }}
