---
# Setup my_user user account

# In case user already exists this will just update fields.
- name: "Setting Up User {{ my_user.username }}"
  user:
    name: "{{ my_user.username }}"
    comment: "{{ my_user.gecos }}"
    # NOTE: DO NOT set shell as it might not be installed; see user/tasks/shell.yml
    # NOTE: Use system home directory see update command bellow
    move_home: false
    # Set empty password, next task will force user to change it on first login
    password: "{{ '' | password_hash('sha512') }}"
    update_password: on_create
  register: out
  when:
    - my_user.is_local

# NOTE: If user was just created force password change on next login.
# WARN: On WSL there's no PAM login so user has to passwd otherwise will be
# kept with empty password.
- name: "Forcing User {{ my_user.username }} To Change Password"
  command: chage -d0 {{ my_user.username }}
  when:
    - out.changed
    - my_user.is_local
    - not my_facts.has_my_user

# WARN: This is not technically super-correct but will work in most cases.
- name: "Refreshing User Facts"
  set_fact:
    my_user: >
      {{ my_user | xcombine({
        "home": out['home']
      }) }}
    my_facts: >
      {{ my_facts | xcombine({
        "has_my_user": true,
        "has_become_my_user": true
      }) }}
  when:
    - out.changed
    - my_user.is_local

- name: "Adding User {{ my_user.username }} To Groups"
  user:
    name: "{{ my_user.username }}"
    groups: "{{ item }}"
    append: true
  with_items: "{{ my_user.groups }}"
  when:
    - my_facts.has_my_user
    - my_user.is_local
    - item in ansible_facts.getent_group
