---
# Setup Chocolatey

# Install latest Chocolatey
# NOTE: Needs chocolatey community source temporarily enabled.
# TODO: Figure out how to update chocolatey using local source?
- name: "Installing Chocolatey"
  win_chocolatey:
    name: chocolatey
    state: present

- name: "Disabling Chocolatey Community Source"
  win_chocolatey_source:
    name: chocolatey
    state: disabled

- name: "Enabling Chocolatey Local Source"
  win_chocolatey_source:
    name: local
    source: "{{ my_facts.win_choco_source }}"
    state: present
  when:
    - my_facts.win_choco_source
