---
# Setup Chocolatey

# NOTE: Temporarily enable "chocolatey" community source to upgrade choco.
- win_chocolatey_source:
    name: chocolatey
    state: present
  when:
    - my_facts.has_choco

- name: "Installing Chocolatey"
  win_chocolatey:
    name: chocolatey
    state: latest
  register: out
# NOTE: Update has_choco and choco_source_dir facts if just installed
- include_role:
    name: _common
    tasks_from: checks/check_choco
  when:
    out: changed

- name: "Installing Chocolatey-AU"
  win_chocolatey:
    name: chocolatey-au
    state: latest

- name: "Disabling Chocolatey Community Source"
  win_chocolatey_source:
    name: chocolatey
    state: disabled

- name: "Enabling Chocolatey Local Source"
  win_chocolatey_source:
    name: local
    source: "{{ choco_source_dir }}"
    state: present
  when:
    - choco_source_dir

# NOTE: Install packages
- include_role:
    name: _common
    tasks_from: win_choco_packages
