# Disable OneDrive

# Find and remove OneDrive Client Installations
- win_reg_stat:
    path: "{{ item }}"
    name: "UninstallString"
  with_items:
    - "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\OneDriveSetup.exe"
    - "HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\OneDriveSetup.exe"
  register: out
- name: Uninstalling OneDrive
  win_command:
    # NOTE: OneDrive has mallformed UninstallString in registry, hence
    # xwinuninstr (see filter_plugins/xwin.py).
    cmd: "{{ item | xwinuninstr }}"
  with_items: '{{ out.results | selectattr("exists") | map(attribute="value") }}'
  when: out.results | map(attribute="exists") | xany

- name: Disabling OneDrive Policies
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "dword"
  with_items:
    # Disable OneDrive group policies
    - path: "HKLM:\\SOFTWARE\\Wow6432Node\\Policies\\Microsoft\\Windows\\OneDrive"
      name: "DisableFileSyncNGSC"
      data: 0x00000001
    - path: "HKLM:\\SOFTWARE\\Wow6432Node\\Policies\\Microsoft\\Windows\\OneDrive"
      name: "DisableFileSync"
      data: 0x00000001
    # Remove Explorer.exe sidebar
    - path: "HKCR:\\CLSID\\{018D5C66-4533-4307-9B53-224DE2ED1FE6}"
      name: "System.IsPinnedToNameSpaceTree"
      data: 0x00000000
    - path: "HKCR:\\Wow6432Node\\CLSID\\{018D5C66-4533-4307-9B53-224DE2ED1FE6}"
      name: "System.IsPinnedToNameSpaceTree"
      data: 0x00000000
  loop_control:
    label: "{{ item.path }}.{{ item.name }}={{ item.data }}"
