---
# Configure Windows network

- name: Adding Windows Local Trusted Hosts
  win_regedit:
    path: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ZoneMap\\Domains\\{{ item.domain }}\\{{ item.host }}"
    name: "{{ item.protocol }}"
    data: 0x00000001
    type: "dword"
  loop_control:
    label: "{{ item.host }}.{{ item.domain }} {{ item.protocol }}"
  with_items: "{{ windows_trusted_hosts }}"

- name: Enabling Administrator Access To Mapped Drives
  win_regedit:
    path: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System"
    name: "EnableLinkedConnections"
    data: 0x00000001
    type: "dword"

# Security

# NOTE: Link-Local Multicast Name Resolution (LLMNR) protocol, a protocol that
# allow name resolution without the requirement of a DNS server.
- name: Disabling LLMNR
  win_regedit:
    path: "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient"
    name: "EnableMulticast"
    data: 0x00000000
    type: "dword"
