---
# Configure Windows networking

- name: Adding Windows local intranet trusted hosts
  win_regedit:
    path: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ZoneMap\\Domains\\{{ item.domain }}\\{{ item.host }}"
    name: "{{ item.protocol }}"
    data: 0x00000001
    type: "dword"
  loop_control:
    label: "{{ item.host }}.{{ item.domain }} {{ item.protocol }}"
  with_items: "{{ windows_trusted_hosts }}"
