---
# Debloat Windows
# NOTE: This should run as user for which setup is made (see main.yml)

- name: Uninstalling Pre-Installed Apps
  win_package:
    product_id: "{{ item }}"
    state: absent
  with_items:
    # Appx
    - Clipchamp.Clipchamp
    - DolbyLaboratories.DolbyAccess
    - Microsoft.3DBuilder
    - Microsoft.WindowsAlarms
    - Microsoft.windowscommunicationsapps
    - Microsoft.Windows.Photos
    - Microsoft.Todos
    - Microsoft.ScreenSketch
    - Microsoft.MicrosoftOfficeHub              # Get Office 365
    - Microsoft.BingNews
    - Microsoft.BingWeather
    - Microsoft.BingFinance
    - Microsoft.BingHealthAndFitness
    - Microsoft.BingFoodAndDrink
    - Microsoft.BingSports
    - Microsoft.BingTravel
    - Microsoft.WindowsMaps
    - Microsoft.ZuneMusic                       # Groove Music
    - Microsoft.ZuneVideo                       # Movies & TV
    - Microsoft.XboxGamingOverlay               # Xbox
    - Microsoft.Xbox.TCUI
    - Microsoft.XboxApp
    - Microsoft.XboxGameOverlay
    #- Microsoft.XboxIdentityProvider           # WARN: breaks game logins
    - Microsoft.XboxSpeechToTextOverlay
    - Microsoft.YourPhone                       # Phone Companion
    - Microsoft.WindowsPhone
    - Microsoft.OneConnect                      # Paid Wifi & Cellular
    - Microsoft.Getstarted
    - Microsoft.GetHelp
    - Microsoft.MicrosoftSolitaireCollection
    - Microsoft.OneDriveSync                    # OneDrive
    - MicrosoftTeams
    - Microsoft.549981C3F5F10                   # Cortana
    - Microsoft.PowerAutomateDesktop
    # Registry
    - OneDriveSetup.exe                         # OneDrive

- name: Disabling ContentDeliveryManager Bloatware
  win_regedit:
    path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager"
    name: "{{ item }}"
    data: 0x00000000
    type: "dword"
  with_items:
    - ContentDeliveryAllowed
    - FeatureManagementEnabled
    - SubscribedContentEnabled
    - OemPreInstalledAppsEnabled      # Various "suggested" apps
    - PreInstalledAppsEnabled
    - PreInstalledAppsEverEnabled
    - SilentInstalledAppsEnabled
    - SystemPaneSuggestionsEnabled
    - SoftLandingEnabled              # Windows Tips and Feedback
    - SubscribedContent-310093Enabled # Welcome To Windows
    - SubscribedContent-338388Enabled # Complete Device Settings
    - SubscribedContent-338389Enabled # Windows Tips
    - SubscribedContent-338393Enabled # Windows Settings Tips
    - SubscribedContent-353694Enabled
    - SubscribedContent-353696Enabled

- name: Disabling \"Get The Most Out Of Windows\" Bloatware
  win_regedit:
    path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager"
    name: "ScoobeSystemSettingEnabled"
    data: 0x00000000
    type: "dword"

- name: Disabling Feedback Requests
  win_regedit:
    path: "HKCU:\\Software\\Microsoft\\Siuf\\Rules"
    name: "NumberOfSIUFInPeriod"
    data: 0x00000000
    type: "dword"

# Services

- name: Disabling Unwanted Services
  win_service:
    name: "{{ item }}"
    state: stopped
    start_mode: disabled
  with_items:
    - WerSvc            # Error Reporting; See also QueueReporting in Scheduled Tasks
    - WpcMonSvc         # Windows Parental Control
    - Fax
    - lfsvc             # Geolocation
    - MSDTC             # NOTE: Run 'dcomcnfg', look at Component Services > Computers > My Computer > Distributed Transaction... > Transaction Statistic, if 0 disable
    #- DoSvc            # Windows Update Delivery Optimization p2p WARN: likely requires to be System?
    - WalletService     # ???
    - SSDPSRV           # UPnP client and server
    - MapsBroker        # Windows Maps download manager
    - AxInstSV          # ActiveX control from Internet authenticator???
    - SysMain           # SuperFetch TODO: see if it hinders system 
    #- OneSync          # WARN: breaks syncing settings
    #- Spooler          # WARN: breaks printing
    #- StiSvc           # WARN: breaks scanning/camera
    #- StorSvc          # WARN: required for WSL2 and HyperV
    #- Winmgmt          # WARN: required for WinRM, remoting, etc.
    #- Ndu              # Network data usage monitor WARN: might break metered connections?
    #- DusmSvc          # Data usage monitor WARN: might break metered network limits, etc.
    #- trkwks           # WARN: breaks NTFS sharing across LAN?

# Scheduled Tasks

- name: Disabling Unwanted Scheduled Tasks
  win_scheduled_task:
    name: "{{ item.task }}"
    path: "{{ item.path }}" 
    enabled: false
  with_items:
    - { path: \Microsoft\Windows\Defrag, task: ScheduledDefrag }
    - { path: \Microsoft\Windows\Windows Error Reporting, task: QueueReporting } # NOTE: WerSvc
    - { path: \Microsoft\XblGameSave, task: XblGameSaveTask }

# Startup Tasks

- name: Disabling Startup Tasks
  xwin_startup_app:
    name: "{{ item }}"
    enabled: false
  with_items:
    - "OneDrive"
    - "AdobeAAMUpdater-1.0"
    - "Adobe CCXProcess"
    - "Adobe Creative Cloud"
    - "Xilinx Information Center.lnk"
    - "91750D7E.Slack_8she8kybcnzg4"
    - "Microsoft.WindowsTerminal_8wekyb3d8bbwe"

# Telemetry

# WARN: Disabling telemetry completely breaks Windows Update
- name: Setting Telemetry Data To Minimum
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "dword"
  with_items:
    - path: "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection"
      name: "AllowTelemetry"
      data: 0x00000001 # 1-Send only _REQUIRED_ data
    - path: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\DataCollection"
      name: "MaxTelemetryAllowed"
      data: 0x00000001 # 1-Send only _REQUIRED_ data
    - path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Diagnostics\\DiagTrack"
      name: "ShowedToastAtLevel"
      data: 0x00000001

# Privacy

- name: Disabling Personalised Ads
  win_regedit:
    path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\AdvertisingInfo"
    name: "Enabled"
    data: 0x00000000
    type: "dword"

- name: Disabling Tailored Experiences
  win_regedit:
    path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Privacy"
    name: "TailoredExperiencesWithDiagnosticDataEnabled"
    data: 0x00000000
    type: "dword"

# Integrations
# Remove various integrations from Start menu, Explorer, etc.

- name: Disabling OneDrive
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "dword"
  with_items:
    # Disable OneDrive group policies
    - path: "HKLM:\\SOFTWARE\\Wow6432Node\\Policies\\Microsoft\\Windows\\OneDrive"
      name: "DisableFileSyncNGSC"
      data: 0x00000001
    - path: "HKLM:\\SOFTWARE\\Wow6432Node\\Policies\\Microsoft\\Windows\\OneDrive"
      name: "DisableFileSync"
      data: 0x00000001
    # Remove Explorer.exe sidebar
    - path: "HKCR:\\CLSID\\{018D5C66-4533-4307-9B53-224DE2ED1FE6}"
      name: "System.IsPinnedToNameSpaceTree"
      data: 0x00000000
    - path: "HKCR:\\Wow6432Node\\CLSID\\{018D5C66-4533-4307-9B53-224DE2ED1FE6}"
      name: "System.IsPinnedToNameSpaceTree"
      data: 0x00000000
  register: out_onedrive

- name: Disabling Bing Search
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "dword"
  with_items:
    - path: "HKCU:\\Software\\Policies\\Microsoft\\Windows\\Explorer"
      name: "DisableSearchBoxSuggestions"
      data: 0x00000001
    - path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Search"
      name: "BingSearchEnabled"
      data: 0x00000000
    - path: "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Dsh"
      name: "AllowNewsAndInterests"
      data: 0x00000000
  register: out_bing

- name: Disabling Cortana
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "dword"
  with_items:
    - path: "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search"
      name: "ConnectedSearchPrivacy"
      data: 0x00000003
    - path: "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search"
      name: "ConnectedSearchUseWeb"
      data: 0x00000000
    - path: "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search"
      name: "ConnectedSearchUseWebOverMeteredConnections"
      data: 0x00000000
    - path: "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search"
      name: "DisableWebSearch"
      data: 0x00000001
    - path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Search"
      name: "CortanaEnabled"
      data: 0x00000000
    - path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Search"
      name: "CanCortanaBeEnabled"
      data: 0x00000000
    - path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Search"
      name: "CortanaConsent"
      data: 0x00000000
  register: out_cortana

- name: Disabling CD Burning
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "dword"
  with_items:
    - path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer"
      name: "NoCDBurning"
      data: 0x00000001
  register: out_cdrw

- name: Disabling XBox
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "dword"
  with_items:
    - path: "HKCU:\\Software\\Microsoft\\GameBar"
      name: "AutoGameModeEnabled"
      data: 0x00000000
    - path: "HKCU:\\Software\\Microsoft\\GameBar"
      name: "ShowStartupPanel"
      data: 0x00000000
    - path: "HKCU:\\System\\GameConfigStore"
      name: "GameDVR_Enabled"
      data: 0x00000000
    - path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\GameDVR"
      name: "AppCaptureEnabled"
      data: 0x00000000
    - path: "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\GameDVR"
      name: "GameDVR"
      data: 0x00000000

- name: Restarting Explorer
  win_shell: Stop-Process -Name explorer -Force
  when:
    - "out_bing.changed or out_cortana.changed or out_cdrw.changed or out_onedrive.changed"
