# Configure NTP servers

- name: Setting NTP Server
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "string"
  with_items:
    - path: "HKLM:\\SYSTEM\\CurrentControlSet\\services\\W32Time\\Parameters"
      name: "NtpServer"
      data: "{{ ntp_server }}"
    # Fix Control Panel
    - path: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\DateTime\\Servers"
      name: "3"
      data: "{{ ntp_server }}"
    - path: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\DateTime\\Servers"
      name: "(Default)"
      data: "3"
  register: out
  loop_control:
    label: "{{ item.path }}.{{ item.name }}={{ item.data }}"

- name: Restarting w32time Service
  win_service:
    name: w32time
    state: restarted
  when:
    - out.changed
