---
# Configure WSL

- name: Converting /tmp To tmpfs
  lineinfile:
    path: /etc/fstab
    regexp: "^tmpfs	/tmp	tmpfs	defaults	1 0$"
    line: "tmpfs	/tmp	tmpfs	defaults	1 0"
  register: out_wsl_tmpfs
  when:
    - my_facts.is_wsl

- name: Installing WSLInterop.conf to binfmt.d
  copy:
    src: "{{ role_path }}/files/binfmt.d/WSLInterop.conf"
    dest: "/etc/binfmt.d/WSLInterop.conf"
    owner: root
    group: root
    mode: 644
    force: true
  register: out_wsl_wslinterop
  when:
    - my_facts.is_wsl

- name: Installing wsl.conf
  copy:
    src: "{{ role_path }}/files/wsl.conf"
    dest: "/etc/wsl.conf"
    owner: root
    group: root
    mode: 644
    force: true
  register: out_wsl_wslconf
  when:
    - my_facts.is_wsl

- name: Installing WSL Scripts
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/usr/local/bin"
    owner: root
    group: root
    mode: 755
    force: true
  with_items:
    - wsl_clocksync
  when:
    - my_facts.is_wsl
  tags: debug

# Terminate WSL to force picking up changes made above
- name: Restarting WSL
  command: "/mnt/c/Windows/System32/wsl.exe -t {{ my_facts.wsl_distro }}"
  when: 
    - (out_wsl_tmpfs.changed or out_wsl_wslinterop.changed or out_wsl_wslconf.changed)
    - my_facts.is_wsl
