---
# Configure WSL
# WARN: Depends on systemd and systemd-sysv being installed by apt.yml!

# TODO: Check if WSL's "init" still relies on /etc/fstab and see if systemd
# unit would do this better?
- name: Installing Empty /etc/fstab
  copy:
    content: ""
    dest: /etc/fstab
    owner: root
    group: root
    mode: 644
    force: false
  when:
    - my_facts.is_wsl

- name: Converting /tmp To tmpfs
  lineinfile:
    path: /etc/fstab
    regexp: "^tmpfs	/tmp	tmpfs	defaults	1 0$"
    line: "tmpfs	/tmp	tmpfs	defaults	1 0"
  register: out_wsl_tmpfs
  when:
    - my_facts.is_wsl

- name: Installing wsl.conf
  template:
    src: "{{ role_path }}/files/wsl.conf.j2"
    dest: "/etc/wsl.conf"
    owner: root
    group: root
    mode: 644
    force: true
  register: out_wsl_wslconf
  when:
    - my_facts.is_wsl

- name: Installing .wslconfig
  template:
    src: "{{ role_path }}/files/wslconfig.j2"
    dest: "/etc/wsl.conf"
    owner: root
    group: root
    mode: 644
    force: true
  register: out_wsl_wslconfig
  when:
    - my_facts.is_wsl

# TODO: Restart here!, maybe use https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_handlers.html

- name: Installing WSLInterop.conf to binfmt.d
  file:
    path: /etc/binfmt.d
    state: directory
- copy:
    src: "{{ role_path }}/files/binfmt.d/WSLInterop.conf"
    dest: /etc/binfmt.d/WSLInterop.conf
    owner: root
    group: root
    mode: 644
    force: true
  register: out_wsl_wslinterop
  when:
    - my_facts.is_wsl

- name: Enabling systemd-binfmt Unit
  systemd:
    name: systemd-binfmt
    enabled: true
    state: started
  when:
    - my_facts.is_wsl
    - my_facts.has_systemd

- name: Installing WSL Scripts
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/usr/local/bin"
    owner: root
    group: root
    mode: 755
    force: true
  with_items:
    - wsl_clocksync
    - wsl_hosts
    - wsl_resolvconf
  when:
    - my_facts.is_wsl

- name: Installing WSL systemd Units
  copy:
    src: "{{ role_path }}/files/systemd/{{ item }}"
    dest: "/etc/systemd/system"
    owner: root
    group: root
    mode: 644
    force: true
  with_items:
    - wsl_hosts.service
  when:
    - my_facts.is_wsl

- name: Enabling WSL systemd Units
  systemd:
    name: "{{ item }}"
    daemon_reload: true
    enabled: true
    state: started
  with_items:
    - wsl_hosts.service
  when:
    - my_facts.has_systemd
    - my_facts.is_wsl

- name: Unmasking systemd-logind
  systemd:
    name: systemd-logind
    masked: false
  when:
    - my_facts.has_systemd

# NOTE: Linger session assures /run/user/UID is owned by user even when not
# logging in through PAM (which is in case of WSL)
- name: Setting {{ my_user.username }} Session Linger
  shell: |
    loginctl show-user -p Linger {{ my_user.username }}
    loginctl enable-linger {{ my_user.username }}
  register: out_wsl_linger
  changed_when: out_wsl_linger.stdout == "no"
  when:
    - my_facts.has_systemd
    - my_facts.is_wsl

# TODO: Make this better to restart right after systemd is enabled!
# Terminate WSL to force picking up changes made above
- name: Restarting WSL
  command: "/mnt/c/Windows/System32/wsl.exe -t {{ my_facts.wsl_distro }}"
  when: 
    - (out_wsl_tmpfs.changed or out_wsl_wslinterop.changed or out_wsl_wslconf.changed or out_wsl_linger.changed)
    - my_facts.is_wsl
