#!/usr/bin/env zsh
# fortune - print random fortune cookie

# Usage: fortune ~/.local/share/fortunes/*
#        fortune -p "\e[1;31m> " -s "\e[0m" ~/.local/share/fortunes/*
fortune() {
	local db=()
        local quote=
	typeset -A opts
	zparseopts -D -E -- p:=opts s:=opts

	for arg in $@; do
		local file=( ${(f)"$(<$arg)"} )
		for line in $file; do
			if [[ ${line// /} == '%' ]]; then
				[[ -n $quote ]] && db+=( $quote )
				quote=
			else
				line="${opts[-p]}$line${opts[-s]}"
				[[ -z $quote ]] && quote=$line || quote+="\n$line"
			fi
		done
	done

	[ ${#db[@]} -ne 0 ] || return
	echo ${db[${RANDOM}%${#db}+1]}
}

fortune $@
