#!/usr/bin/zsh
# ~/.zsh/ls - ls command wrapper

# Usage: ls [args...]


ls () {
    local args=()
    # Check if .lsignore exists, if so read all entries and pass them as -I
    [ -r ./.lsignore ] && while read -r line ; do
        [[ -n "$line" && "$line" != [[:blank:]#]* ]] \
            && args+=(-I $line)
    done < ./.lsignore

    # Run ls with additionali arguments
    command ls ${args[@]} $@
}

ls $@
