#!/usr/bin/zsh
# ~/.zsh/motd - Print MOTD

# Usage: motd [/path/to/db]

zmodload zsh/mapfile

# TODO Maybe come up with some caching mechanism, but this itself is fast
# enough and called once on login...
# TODO Add colors...
motd () {
    [ ! -z $1 ] && [ -r $1 ] || return 1

    # Process file
    local file=( "${(f)mapfile[$1]}" )
    local db=()
    local quote
    for line in $file; do
        if [ "${line// /}" = "%" ]; then
            [ ! -z "$quote" ] && db+=("$quote")
            quote=
            continue
        fi
        [ -z "$quote" ] && quote="$line" || quote="$quote\n$line"
    done
    # There are no quotes in database, exit
    [ ${#db[@]} -ne 0 ] || return 2

    # Pick random quote and print it
    quote=$db[${RANDOM}%${#db}+1]
    print $quote
}

motd $@
