#!/usr/bin/env zsh
# psef - grep ps output

# Usage: psef [rsync xz]
psef() {
	local p= h=
	for p in ${(f@)"$(ps -ecwww -o user,pid,ppid,%cpu,%mem,stime,time,state,ni,comm,args)"}; do
		[[ -z $h ]] && { echo $p ; h=1 ; continue }
		[[ ${${=p}:9:l} =~ ^(${${(j:|:)@:l}:-\.\*}) ]] && echo "$p"
	done
}

psef $@
