#!/usr/bin/zsh
# Python virtual environments management wrapper

# Usage: venv [/path/to/python]

venv () {
    # Sanity check, don't deactivate automatically
    if [ ! -z $VIRTUAL_ENV ]; then
        (>&2 echo "error: other virtualenv activated, run 'deactivate'!")
        exit 1
    fi

    # Find interpreter (default is just 'python') and its major.minor version.
    local python=$(whence -cap ${1:-python}|head -1)
    local ver=$($python -c 'import sys;print("%s%s" % sys.version_info[:2])')
    local venv="${2:-.}/venv${ver}_${OSARCH}"

    # Check if venv already exists, if not create it
    if [ ! -d $venv ]; then
        virtualenv -p $python $venv
    fi
    source $venv/bin/activate
    # TODO Update variable used by prompt
}

venv $@
