---
# Check WinRM connection
#
# Check if WinRM connection can be established with host that not necessarily
# has to be part of inventory.
#
# NOTE: vars: need to be set for this to work: winrm_test_host,
#       winrm_test_clientcert, winrm_test_clientkey.
# NOTE: Sets my_facts.can_winrm and my_facts.has_pywinrm

- name: "Checking If Ansible Can WinRM To {{ winrm_host }}"
  xtest_winrm:
    hostname: "{{ winrm_host }}"
    winrm_transport: certificate
    winrm_cert_pem: "{{ winrm_clientcert }}"
    winrm_cert_key_pem: "{{ winrm_clientkey }}"
    winrm_server_cert_validation: ignore
  register: out
- set_fact:
    my_facts: >
      {{
        my_facts | xcombine({
          "can_winrm": out.can_winrm,
          "has_pywinrm": out.has_pywinrm
        })
      }}
