---
# Create and remove directories
#
# NOTE: vars: need to be set for this to work; prefix variable is added in
# front of each directory path and dirs variable.

# Linux
- block:

  - name: "Creating {{ label }} Directories"
    xdir:
      path: "{{ prefix + item.path }}"
      state: "{{ item.state | default(omit) }}"
      link: "{{ item.link | default(omit) }}"
      move: "{{ item.move | default(omit) }}"
    loop_control:
      label: "{{ item.path }}"
    with_items: "{{ dirs }}"

  when:
    - ansible_facts.system in ("Linux",)

# Windows
- block:

  - name: "Creating {{ label }} Directories"
    xwin_dir:
      path: "{{ prefix + item.path | xwin_path }}"
      state: "{{ item.state | default(omit) }}"
      link: "{{ item.link | default(omit) }}"
      move: "{{ item.move | default(omit) }}"
    loop_control:
      label: "{{ item.path }}"
    with_items: "{{ dirs }}"

  when:
    - ansible_facts.os_family in ("Windows",)
