---
# Development role variables

# Additional packages to install
apt_packages:
  - gdb                       # GNU debugger
  - golang
  - gcc
  - g++
  - libstdc++6                # GNU C++ standard library
  - libstdc++-10-dev
  - build-essential
  - binutils
  - gcc-avr                   # gcc for AVR microcontrollers
  - avrdude                   # AVR microcontrollers download/upload tool
  - clang                     # c/c++ frontend for LLVM
  - clangd                    # language server for clang
  - clang-format
  - clang-tidy
  - libc++1                   # clang C++ standard library
  - libc++abi1
  - libc++-dev
  - libc++abi-dev
  - libclang-dev
  - libclang1
  - python3-clang
  - llvm                      # LLVM
  - llvm-runtime
  - lld                       # LLVM linker
  - lldb                      # lldb next-gen debugger
  - yasm                      # modular assembler (successor of nasm)
  - cmake
  - ninja-build               # small fast build system
  #- googletest               # DO NOT USE system googletest
  # Dynamnic languages
  - nodejs
  - python3
  - python3-dev
  - python3-pip               # python package manager
  - python3-venv              # python virtual environments
  - ruby
  - ruby-dev                  # required for some bundler packages
  - bundler                   # ruby package manager
  # Various clients
  - postgresql-client         # postgresql client
  - mysql-client              # mysql client
  - docker-ce-cli             # docker client
  - docker-compose
  - kubectl
  - google-cloud-sdk          # gcloud utility and other Google Cloud tools
  # General Linux stuff
  - pkg-config
  - libtool-bin
  # Ubuntu/Debian packaging
  - devscripts
  - dput
  - quilt
  - fakeroot
  # Misc
  - protobuf-compiler         # protocol buffers compiler
  - manpages-dev
  - sloccount                 # count sloc
  - tig
  - zlib1g-dev

# Go packages
go_packages:
  - golang.org/x/tools/gopls
  - golang.org/x/tools/cmd/goimports
  - golang.org/x/tools/cmd/godoc
  - golang.org/x/lint/golint
  - google.golang.org/protobuf/cmd/protoc-gen-go
  - google.golang.org/grpc/cmd/protoc-gen-go-grpc
  - github.com/go-delve/delve/cmd/dlv
  - honnef.co/go/tools/cmd/staticcheck
  # NOTE: For golangci-lint see tasks/go.yml; DO NOT put it here

# Python packages
python_packages:
  - black                     # opinionated code formatter
  - flake8                    # pep8 checker
  - isort                     # import sorter
  - mypy
  - mypy-ls                   # mypy support in lsp
  - poetry                    # dependency manager (replaces setup.py)
  - pylint                    # static code checker
  - pyls-isort                # isort support in lsp
  - pytest
  - python-lsp-black          # black support in lsp
  - python-lsp-server
  - sphinx                    # documentation generator

# Node.js packages
nodejs_packages:
  - eslint
  - prettier
  - typescript
  - typescript-language-server
  - yarn
