#!/bin/bash
# Set WSL instance clock to same value as host (without using network)

# Trigger from Windows scheduler
# Log: System
# Source: Kernel-Power
# Event ID: 507 NOTE: Modern Standby

PS=/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
DATE=$($PS -Command "get-date -UFormat \"%a, %d %b %Y %T %Z00\"")

date -R -s "$DATE"
