#!/bin/bash
# Add Windows IP to /etc/hosts
# NOTE: This is just workaround based on fact that Hyper-V nameserver is also
# the host running WSL.

[ ! -r /mnt/wsl/resolv.conf ] && exit
while read -r opt ip; do
    if [ $opt == "nameserver" ]; then
        if [ -z ${HEAD+x} ]; then
            echo " " >> /etc/hosts
            echo "# The following line(s) are added by wsl_hosts script" >> /etc/hosts
            HEAD=1
        fi
        echo "$ip	$(hostname).win" >> /etc/hosts
    fi
done < /mnt/wsl/resolv.conf
