---

- name: Linux
  hosts: linux

  pre_tasks:
    - import_tasks: tasks/pre_args.yml
    - import_tasks: tasks/pre_user.yml
    - import_tasks: tasks/pre_ansible.yml
    - import_tasks: tasks/debug.yml
