---

- name: Linux
  hosts: linux
  pre_tasks:
    - { import_tasks: tasks/pre_linux.yml, tags: always }
    - { import_tasks: tasks/pre_lan.yml, tags: always }
    - { import_tasks: tasks/pre_wsl.yml, tags: always }
    - { import_tasks: tasks/pre_bitwarden.yml, tags: always }
    - { import_tasks: tasks/pre_debug.yml, tags: [debug, never] }
  post_tasks:
    - { import_tasks: tasks/post_wsl.yml, tags: always }
  roles:
    - { role: os,     tags: [os, linux] } 
    - { role: user,   tags: [user, linux] }
    - { role: devel,  tags: [devel, linux, never] }
    - { role: kube,   tags: [kube, linux, never] }

- name: Windows
  hosts: windows
  pre_tasks:
    - { import_tasks: tasks/pre_windows.yml, tags: always }
    - { import_tasks: tasks/pre_lan.yml, tags: always }
    - { import_tasks: tasks/pre_bitwarden.yml, tags: always }
    - { import_tasks: tasks/pre_debug.yml, tags: [debug, never] }
  post_tasks:
  roles:
    - { role: os,     tags: [os, windows] }
    - { role: user,   tags: [user, windows] }
    - { role: devel,  tags: [devel, windows, never] }
    - { role: kube,   tags: [kube, windows, never] }
