---

- name: Linux
  hosts: linux
  pre_tasks:
    - { import_tasks: tasks/pre_linux.yml, tags: always }
    - { import_tasks: tasks/pre_wsl.yml, tags: always }
    - { import_tasks: tasks/pre_bitwarden.yml, tags: always }
  roles:
    - { role: os,     tags: [os, linux] } 
    - { role: user,   tags: [user, linux] }
    - { role: devel,  tags: [devel, linux] }

- name: Windows
  hosts: windows
  pre_tasks:
    - { import_tasks: tasks/pre_windows.yml, tags: always }
    - { import_tasks: tasks/pre_bitwarden.yml, tags: always }
  roles:
    - { role: os,     tags: [os, windows] }
    - { role: user,   tags: [user, windows] }
    - { role: devel,  tags: [devel, windows] }
