---
# User-level directories

# Linux
- include_role:
    name: _common
    tasks_from: dirs.yml
  vars:
    label: "User"
    # WARN: DO NOT use dirs: {{ dirs }} as variable (recursion)
    dirs: "{{ user_dirs }}"
    prefix: "{{ my_user.home }}"
  when:
    - ansible_facts.system in ("Linux",)

# Windows
- block:
  - include_role:
      name: _common
      tasks_from: win_dirs.yml
    vars:
      label: "User"
      # WARN: DO NOT use dirs: {{ dirs }} as variable (recursion)
      dirs: "{{ user_dirs }}"
      prefix: "{{ my_user.win_userprofile }}\\"

  - name: "Creating desktop.ini"
    xwin_desktop_ini:
      path: "{{ my_user.win_userprofile }}\\{{ item.path | xwin_path }}"
      icon: "{{ item.win_icon }}"
    loop_control:
      label: "{{ item.path }}"
    with_items: "{{ user_dirs | selectattr('win_icon', 'defined') }}"

  - name: "Relocating User Shell Folders"
    xwin_shell_folder:
      guid: "{{ item.win_guid }}"
      path: "{{ my_user.win_userprofile }}\\{{ item.path | xwin_path }}"
      move_files: true
    loop_control:
      label: "{{ item.path }}"
    with_items: "{{ user_dirs | selectattr('win_guid', 'defined') }}"

  - name: "Removing Unwanted Directories"
    win_file:
      path: "{{ my_user.win_userprofile }}\\{{ item }}"
      state: "absent"
    ignore_errors: true
    with_items:
      - "ansel"       # Nvidia
      - "Contacts"
      - "Desktop"
      - "Downloads"
      - "Favorites"
      - "Links"
      - "OneDrive"
      - "Pictures"
      - "Saved Games"
      - "Searches"
      - "source"      # Visual Studio

  # NOTE: These files prevent Windows and apps from creating directories that I
  # don't want.
  - name: "Creating Decoy Files"
    win_shell: |
      $changed = 0
      if (!(Test-Path -Path {{ item }} -PathType leaf)) {
        $f = New-Item -Path {{ item }}
        $f.Attributes += "Hidden"
        $changed = 1
      }
    args:
      chdir: "{{ my_user.win_userprofile }}"
    register: result
    changed_when: result.stdout | int > 0
    with_items:
      - "ansel"
      - "source"

  when:
    - ansible_facts.os_family in ("Windows",)
