---
# Clone and update dotfiles
# See also: windows_dotfiles.yml

# NOTE: Depends on git being installed by os role and in PATH.
- name: Cloning Dotfiles Repository {{ dotfiles_repo }}
  # NOTE: Not using builtin.git as we clone to ~ which already exists.
  shell:
    chdir: "{{ my_user.home }}"
    cmd: |
      umask {{ my_user.umask }}
      git init --separate-git-dir .dfgit
      git --git-dir=.dfgit remote add -f -m main origin https://github.com/{{ dotfiles_repo }}
      git --git-dir=.dfgit reset --hard origin/main
      git --git-dir=.dfgit checkout main
      [ -f .git ] && rm -rf .git
    creates: "{{ my_user.home }}/.dfgit"
  register: out

- name: Updating Dotfiles
  shell:
    chdir: "{{ my_user.home }}"
    cmd: |
      umask {{ my_user.umask }}
      git --git-dir=.dfgit pull --ff-only
  register: result
  changed_when: result.stdout != "Already up to date."
  ignore_errors: true # NOTE: When fast-forward not possible
  when:
    - not out.changed
