---
# Clone and update dotfiles
# NOTE: Depends on git being installed by os role and in PATH.

- name: "Cloning Dotfiles Repository {{ dotfiles }}"
  # NOTE: Not using builtin.git as we clone to ~ which already exists.
  shell:
    chdir: "{{ my_user.home }}"
    cmd: |
      umask {{ my_user.umask }}
      git init --separate-git-dir .dfgit -b main
      git --git-dir=.dfgit remote add -f -m main origin https://github.com/{{ dotfiles }}
      git --git-dir=.dfgit reset --hard origin/main
      git --git-dir=.dfgit checkout main
      git --git-dir=.dfgit branch --set-upstream-to=origin/main main
      [ -f .git ] && rm -rf .git
    creates: "{{ my_user.home }}/.dfgit"
  # NOTE: Might require http_proxy
  environment: "{{ env }}"
  register: out

- name: "Updating Dotfiles"
  shell:
    chdir: "{{ my_user.home }}"
    cmd: |
      umask {{ my_user.umask }}
      git --git-dir=.dfgit pull --ff-only
  # NOTE: Might require http_proxy
  environment: "{{ env }}"
  register: result
  changed_when: result.stdout != "Already up to date."
  ignore_errors: true # NOTE: When fast-forward not possible
  when:
    - not out.changed
