---
# User environment setup

# Linux
- block:
    - import_tasks: apt.yml
    - import_tasks: shell.yml
  become: true
  become_user: "root"
  when:
    - ansible_facts.system == "Linux"
    - my_facts.has_become_root

- block:
    - import_tasks: dotfiles.yml
    - import_tasks: dirs.yml
    - import_tasks: secrets.yml
    - import_tasks: dotfiles_ssh.yml
    - import_tasks: nvim.yml
    - import_tasks: nerdfonts.yml
  become: true
  become_user: "{{ my_user.username }}"
  when:
    - ansible_facts.system == "Linux"
    - my_facts.has_become_my_user

# Windows
- block:
    - import_tasks: windows_dotfiles.yml
    - import_tasks: windows_dirs.yml
    - import_tasks: windows_secrets.yml
    - import_tasks: windows_dotfiles_ssh.yml
    - import_tasks: windows_fonts.yml
  # WARN: 'become' to user itself is required to allow credential delegation;
  # user is expected to be an Administrator.
  become: true
  become_user: "{{ my_user.domain_username }}"
  when:
    - ansible_facts.os_family == "Windows"
