---
# User setup

# Linux
- block:
    - import_tasks: deb.yml
      when: ansible_facts.os_family == "Debian"
    - import_tasks: shell.yml
  become: true
  become_user: "root"
  when:
    - ansible_facts.system in ("Linux",)
    - my_facts.has_become_root

- block:
    - import_tasks: dotfiles.yml
    - import_tasks: dirs.yml
      tags: debug
    - import_tasks: secrets.yml
      when: my_control_node_facts.has_bitwarden
    - import_tasks: dotfiles_ssh.yml
  become: true
  become_user: "{{ my_user.username }}"
  when:
    - ansible_facts.system in ("Linux",)
    - my_facts.has_become_my_user

# Windows
- block:
    - import_tasks: win_dotfiles.yml
    - import_tasks: win_dirs.yml
      tags: debug
    - import_tasks: win_shell.yml
  # WARN: 'become' to user itself is required to allow credential delegation;
  # user is expected to be an Administrator.
  become: true
  become_user: "{{ my_user.win_domain_username }}"
  when:
    - ansible_facts.os_family in ("Windows",)
    - my_facts.has_administrator

# NOTE: Run handlers
- meta: flush_handlers
