---
# User environment setup

- debug:
    var: ansible_facts

# Linux
- block:
    - import_tasks: apt.yml
    - import_tasks: shell.yml
  become: true
  become_user: "root"
  when:
    - ansible_facts.system == "Linux"
    - my_facts.has_become_root

- block:
    - import_tasks: dotfiles.yml
    - import_tasks: dirs.yml
    - import_tasks: secrets.yml
    - import_tasks: nvim.yml
  become: true
  become_user: "{{ my_user.username }}"
  when:
    - ansible_facts.system == "Linux"
    - my_facts.has_become_my_user
