---
# Patch Nerd Fonts
# NOTE: Depends on apt.yml installing dependencies

- find:
    paths: "{{ my_user.home }}/.local/share/fonts/truetype/{{ item | dirname }}"
    patterns: "{{ item | basename }}"
    recurse: true
    file_type: file
  with_items: "{{ nerdfonts }}"
  register: out

# This takes long so using creates:; to re-patch simply delete all *NF.[ot]tf:
# $ find ~/.local/share/fonts/truetype -iname \*NF.[ot]tf -delete
# NOTE: Depends on custom font-patcher (~/bin/nerdfonts)
- name: Patching Nerd Fonts
  command:
    cmd: "{{ my_user.home }}/bin/nerdfonts -cslq \"{{ item }}\""
    creates:  "{{ item | regex_replace('^(.*)(\\.[to]tf)$', '\\1 NF\\2') }}"
  # Only files that do not already contain NF.ext
  with_items: "{{ out.results | map(attribute='files') | flatten | map(attribute='path') | reject('regex', 'NF\\.[ot]tf$') }}"
