---
# Install Neovim packs and dictionaries

- name: Installing Neovim Packs
  git:
    repo: "{{ item.repo }}"
    dest: "{{ my_user.home }}/.local/share/nvim/site/pack/{{ item.group }}/{{ 'opt' if item.get('opt', false) else 'start' }}/{{ item.name }}"
  loop_control:
    label: "{{ item.name }} {{ item.repo }}"
  with_items: "{{ nvim_packs }}"

- name: Creating Neovim Spell Directory
  file:
    path: "{{ my_user.home }}/.local/share/nvim/site/spell/"
    state: directory

- name: Installing Neovim Spell Files
  get_url:
    dest: "{{ my_user.home }}/.local/share/nvim/site/spell/"
    url: "https://ftp.nluug.nl/pub/vim/runtime/spell/{{ item }}"
  # NOTE: Ignore errors as some .spl or .sug might be missing
  ignore_errors: true
  loop_control:
    label: "{{ item }}"
  with_items: "{{ nvim_spell | product(['spl', 'sug']) | map('join', '.') | list }}"

- name: Detecting pip3
  command: pip3 --version
  failed_when: false
  changed_when: false
  register: has_pip3

- name: Installing Neovim Python Provider
  shell:
    chdir: "{{ my_user.home }}"
    cmd: |
      umask {{ my_user.umask }}
      pip3 install pynvim
  when:
    - not has_pip3.failed
