---
# Fetch secrets from Bitwarden vault

# SSH keys
- name: Fetching SSH Keys
  copy:
    dest: "{{ my_user.home }}/.ssh/keys/{{ item.0 + item.1 }}"
    mode: "{{ '0600' if item.1 == '' else '0644' }}"
    content: "{{ lookup('bitwarden', 'SSH ' + item.0, attachment=item.0 + item.1) | b64decode }}"
    force: true
  loop_control:
    label: "{{ item.0 }}: {{ item.0 + item.1 }}"
  with_nested:
    - "{{ ssh_keys }}"
    - ["", ".pub"]
  when:
    - my_facts.has_bitwarden

# IRC Client Certificates
- block:
    - name: Creating IRC Client Certificates Directory
      file:
        path: "{{ my_user.home }}/.config/weechat/certs"
        mode: "0700"
        state: directory

    - name: Fetching IRC Client Certificates
      copy:
        dest: "{{ my_user.home }}/.config/weechat/certs/{{ item.server + '_' + item.user + '.pem' }}"
        mode: "0600"
        content: "{{ lookup('bitwarden', 'IRC ' + item.server, attachment=item.server + '_' + item.user + '.pem') | b64decode }}"
      loop_control:
        label: "{{ item.user }}@{{ item.server }}"
      with_items: "{{ irc_certs }}"
  when:
    - my_facts.has_bitwarden

# GPG Keys
- block:
    - name: Detecting GPG
      command: gpg --version
      failed_when: false
      changed_when: false
      register: has_gpg

    - name: Creating GPG Keys Temporary Directory
      tempfile:
        state: directory
      register: tmpdir
      when:
        - not has_gpg.failed

    - name: Fetching GPG Keys
      copy:
        dest: "{{ tmpdir.path }}/{{ item.0 }}{{ item.1 }}"
        content: "{{ lookup('bitwarden', 'GPG ' + item.0, attachment=item.0 + item.1) | b64decode }}"
      loop_control:
        label: "{{ item.0 }}{{ item.1 }}"
      with_nested:
        - "{{ gpg_keys }}"
        - [".priv.asc", ".sub_priv.asc"]
      when:
        - not has_gpg.failed

    - name: Importing GPG Keys
      shell: |
        for F in "{{ item }}.priv.asc" "{{ item }}.sub_priv.asc" ; do
          gpg \
            --batch \
            --yes \
            --pinentry-mode=loopback \
            --passphrase="{{ lookup('bitwarden', 'GPG ' + item, field='fields.Passphrase') }}" \
            --import "{{ tmpdir.path }}"/$F
        done
        # NOTE: Ansible breaks fd 0; workaround using command file
        echo "5\ny\n" > "{{ tmpdir.path }}/command"
        gpg \
          --command-file "{{ tmpdir.path }}/command" \
          --expert \
          --edit-key "{{ item }}" \
          trust
      with_items: "{{ gpg_keys }}"
      when:
        - not has_gpg.failed
  always:
    - name: Deleting GPG Keys Temporary Directory
      file:
        path: "{{ tmpdir.path }}"
        state: absent
      when:
        - tmpdir is defined
  when:
    - my_facts.has_bitwarden
