---
# Change shell to my_user.shell

- name: "Detecting {{ my_user.shell | basename }}"
  stat:
    path: "{{ my_user.shell }}"
  failed_when: false
  changed_when: false
  register: out

- name: "Changing User Shell To {{ my_user.shell | basename }}"
  command: >
    usermod -s {{ my_user.shell }} {{ my_user.username }}
  register: usermod_out
  changed_when: "'usermod: no changes' not in usermod_out.stderr_lines"
  when:
    - not out.failed
