---
# Install Vim files

- name: Installing Vim Spell Files
  get_url:
    dest: "{{ my_user.home }}/.vim/spell/"
    url: "https://ftp.nluug.nl/pub/vim/runtime/spell/{{ item }}"
  # NOTE: Ignore errors as some .spl or .sug might be missing
  ignore_errors: true
  loop_control:
    label: "{{ item }}"
  with_items: "{{ vim_spell | product(['spl', 'sug']) | map('join', '.') | list }}"
