---
# Setup Windows user directories

- name: Hiding Dotfiles
  win_shell: |
    $changed = 0
    $d = @()
    $d += Get-ChildItem {{ my_user.userprofile }} -Filter AppData -Force
    $d += Get-ChildItem {{ my_user.userprofile }} -Filter .* -Force
    $d | foreach {
      if (-Not ($_.Attributes -Match "Hidden")) {
        $_.Attributes += "Hidden"
        $changed += 1
      }
    }
    Write-Host $changed
  register: result
  changed_when: result.stdout | int > 0
  tags: debug

# TODO: Relocate directories (e.g. Videos -> videos, etc.)

- name: Deleting Unwanted Directories
  win_file:
    path: "{{ my_user.userprofile }}\\{{ item }}"
    state: absent
  # NOTE: Some directories might be protected by Windows, skip those.
  ignore_errors: true
  with_items:
    - "OneDrive"
    - "ansel"         # Nvidia
    - "source"        # Visual Studio
