---
# Install fonts

# NOTE: On bare Windows this will not install nerdfonts (that's why we copy
# from WSL).
- win_find:
    paths: "{{ my_facts.wsl_unc_home_dir if my_facts.is_wsl else my_user.userprofile }}\\.local\\share\\fonts\\truetype"
    recurse: true
    hidden: true
    use_regex: true
    patterns: "\\.[ot]tf$"
  register: out

- name: Installing Windows User Fonts
  xwin_font:
    path: "{{ item }}"
    per_user: true
  with_items: "{{ out.files | map(attribute='path') }}"
