---
# Clone and update dotfiles
# See also: dotfiles.yml

# NOTE: Depends on git being installed by os role and in PATH.
- name: Cloning Dotfiles Repository {{ dotfiles_repo }}
  win_shell: |
    & git init --separate-git-dir .dfgit
    & git --git-dir=.dfgit remote add -f -m main origin https://github.com/{{ dotfiles_repo }}
    & git --git-dir=.dfgit reset --hard origin/main
    & git --git-dir=.dfgit checkout main
    Remove-Item .git -ErrorAction Ignore
  args:
    chdir: "{{ my_user.userprofile }}"
    creates: "{{ my_user.userprofile }}\\.dfgit"
  register: out

- name: Updating Dotfiles
  win_shell: |
    & git --git-dir=.dfgit pull --ff-only
  args:
    chdir: "{{ my_user.userprofile }}"
  register: result
  changed_when: result.stdout != "Already up to date.\n"
  ignore_errors: true # NOTE: When fast-forward not possible
  when:
    - not out.changed

- name: Hiding Dotfiles
  win_shell: |
    $changed = 0
    $d = @()
    $d += Get-ChildItem {{ my_user.userprofile }} -Filter AppData -Force
    $d += Get-ChildItem {{ my_user.userprofile }} -Filter .* -Force
    $d | foreach {
      if (-not ($_.Attributes -match "Hidden")) {
        $_.Attributes += "Hidden"
        $changed += 1
      }
    }
    Write-Host $changed
  register: result
  changed_when: result.stdout | int > 0
