---
# Setup Windows cursors

# Install cursor schemes
# BUG: WinRM is unable to broadcast change to running session so cursors will
# change after restart...
- name: Installing Aero Black Cursor Scheme
  xwin_cursor_scheme:
    name: "Aero Black{{ item.name }}"
    select: "{{ item.select }}"
    arrow: "{{ prefix }}_arrow{{ item.suffix }}.cur"
    help: "{{ prefix }}_helpsel{{ item.suffix }}.cur"
    wait: "{{ prefix }}_working{{ item.suffix }}.ani"
    busy: "{{ prefix }}_busy{{ item.suffix }}.ani"
    cross: "{{ prefix }}_cross{{ item.suffix }}.cur"
    ibeam: "{{ prefix }}_beam{{ item.suffix }}.cur"
    pen: "{{ prefix }}_pen{{ item.suffix }}.cur"
    # WARN: no needs to be quoted because YAML...
    "no": "{{ prefix }}_unavail{{ item.suffix }}.cur"
    sizens: "{{ prefix }}_ns{{ item.suffix }}.cur"
    sizewe: "{{ prefix }}_ew{{ item.suffix }}.cur"
    sizenwse: "{{ prefix }}_nwse{{ item.suffix }}.cur"
    sizenesw: "{{ prefix }}_nesw{{ item.suffix }}.cur"
    sizeall: "{{ prefix }}_move{{ item.suffix }}.cur"
    uparrow: "{{ prefix }}_up{{ item.suffix }}.cur"
    hand: "{{ prefix }}_link{{ item.suffix }}.cur"
    pin: "{{ prefix }}_pin{{ item.suffix }}.cur"
    person: "{{ prefix }}_arrow{{ item.suffix }}.cur"
    state: "present"
  vars:
    prefix: "{{ my_user.userprofile }}\\.local\\share\\icons\\aero_black\\cursors\\aero_black"
  with_items:
    - { name: "", suffix: "", select: true }
    - { name: " (large)", suffix: "_l", select: false }
    - { name: " (extra large)", suffix: "_xl", select: false }
