---
# Fetch secrets from Bitwarden vault
# See also: secrets.yml

# Secrets

# SSH keys
- name: Fetching SSH Keys
  win_copy:
    dest: "{{ my_user.userprofile }}\\.ssh\\keys\\{{ item.0 + item.1 }}"
    content: "{{ lookup('bitwarden', 'SSH ' + item.0, attachment=item.0 + item.1) | b64decode }}"
    force: true
  loop_control:
    label: "{{ item.0 }}: {{ item.0 + item.1 }}"
  with_nested:
    - "{{ ssh_keys }}"
    - ["", ".pub"]
  when:
    - my_facts.has_bitwarden

# Licenses

- block:
  # NOTE: In case software is not installed yet or wasn't run yet.
  - name: Creating License Directories
    win_file:
      path: "{{ item.dest | win_dirname }}"
      state: directory
    loop_control:
      label: "{{ item.dest | win_dirname }}"
    with_items: "{{ licenses | selectattr('os','in','windows,all') }}"

  - name: Fetching Licenses
    win_copy:
      dest: "{{ item.dest }}"
      content: "{{ lookup('bitwarden', item.name, attachment=item.file) | b64decode }}"
      force: true
    loop_control:
      label: "{{ item.name }}"
    with_items: "{{ licenses | selectattr('os','in','windows,all') }}"
  when:
    - my_facts.has_bitwarden
