---
# Clone and update dotfiles
# See: dotfiles.yml

- name: Cloning Dotfiles Repository {{ dotfiles_repo }}
  # NOTE: Depends on git being installed by os role and in PATH
  win_shell: |
    & git init --separate-git-dir .dfgit
    & git --git-dir=.dfgit remote add -f -m main origin https://github.com/{{ dotfiles_repo }}
    & git --git-dir=.dfgit reset --hard origin/main
    & git --git-dir=.dfgit checkout main
    Remove-Item .git -ErrorAction Ignore
  args:
    chdir: "{{ my_user.userprofile }}"
    creates: "{{ my_user.userprofile }}\\.dfgit"
  register: out
