---
# RPM packages variable

rpm_sources:
  - name: "docker"
    desc: "Docker CE"
    repo: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
    key: "https://download.docker.com/linux/rhel/gpg"

rpm_packages:
  - cscope
  - gdb                       # GNU debugger
  - gcc
  - libstdc++                 # GNU C++ standard library
  - libstdc++-devel
  - binutils
  - yasm                      # modular assembler (successor of nasm)
  - cmake
  - ninja-build               # small fast build system
  #- googletest               # WARN: DO NOT USE system googletest
  # Dynamnic languages
  - nodejs                    # WARN: This will break dependence on system nodejs 
  #- npm                      # WARN: DO NOT install as it is bundled with upstream nodejs
  - python3.11
  - python3.11-devel          # python package manager
  - ruby
  - ruby-devel                # required for some bundler packages
  - rubygem-bundler           # ruby package manager
  # Various clients
  - postgresql                # postgresql client
  - mysql                     # mysql client
  - docker-ce-cli             # docker client
  #- kubectl
  #- google-cloud-sdk          # gcloud utility and other Google Cloud tools
  # General Linux stuff
  - pkgconf
  - libtool
  # Misc
  - protobuf-compiler         # protocol buffers compiler
  - sloccount                 # count sloc
  - tig
  - zlib-devel
