---
# APT repositiories and packages variables

apt_packages:
  - apcalc
  - ffmpeg
  - graphicsmagick
  - graphicsmagick-imagemagick-compat
  - weechat                   # irc client
  - xdg-user-dirs
  - mc                        # file manager
  - direnv                    # load .env files
  - fzf                       # fuzzy finder
  - python3-fontforge
  # NOTE: redundant with devel role but required for Nvim on non-dev machines
  - python3-pip

apt_packages_desktop:
  - google-chrome-stable
