---
# User directories variables

# This is shared both by Linux and Windows as I tend to have same home
# directory organization on both systems. On Windows especially there's a lot
# of littering done by Apps so I redirect Documents and all special folders to
# TODO.

# Properties explanation:
# link: "wsl" will link %USERPROFILE%/name to WSL (dirs.yml)
# link: "windows" will link //wsl.local../name to Windows (windows_dirs.yml)
# xdg: "XDG_FOO_DIR" will put directory to ~/.config/user-dirs.dirs or set
# environment variable on Windows to point to that directory.
# windows_guid: windows_guid of special directory (windows_dirs.yml).
# windows_icon: windows_icon of directory (windows_dirs.yml).
# os: "windows" (or "linux") will create directory only on given OS

# WARN: When nesting parent directory has to go first!

user_dirs:
  - name: "bak"                       # backups to pick up
  - name: "desk"                      # desktop
    xdg: "XDG_DESKTOP_DIR"
    windows_guid: "B4BFCC3A-DB2C-424C-B029-7FE99A87C641"
    windows_icon: "%SystemRoot%\\system32\\imageres.dll,-183"
    link: "wsl"
  - name: "docs"                      # documents
    xdg: "XDG_DOCUMENTS_DIR"
    # NOTE: Not linked with windows_guid as Windows apps tend to litter "My Documents" a lot
    windows_icon: "%SystemRoot%\\system32\\imageres.dll,-112"
    link: "wsl"
  - name: "downl"                     # downloads
    xdg: "XDG_DOWNLOAD_DIR"
    windows_guid: "374DE290-123F-4565-9164-39C4925E467B"
    windows_icon: "%SystemRoot%\\system32\\imageres.dll,-184"
    link: "wsl"
  - name: "downl/arch"                # downloads (archived)
  - name: "drive"                     # Google Drive
    windows_icon: "%USERPROFILE%\\.local\\share\\pixmaps\\folder_drive.ico,0"
    link: "wsl"
  - name: "logs"                      # logs (irc, etc.)
    link: "windows"
  - name: "mail"                      # maildir
    link: "windows"
  - name: "music"                     # music
    xdg: "XDG_MUSIC_DIR"
    windows_guid: "4BD8D571-6D19-48D3-BE97-422220080E43"
    windows_icon: "%SystemRoot%\\system32\\imageres.dll,-108"
    link: "wsl"
  - name: "pics"                      # pictures
    xdg: "XDG_PICTURES_DIR"
    windows_guid: "33E28130-4E1E-4676-835A-98395C3BC3BB"
    windows_icon: "%SystemRoot%\\system32\\imageres.dll,-113"
    link: "wsl"
  - name: "pub"                       # public files
    xdg: "XDG_PUBLICSHARE_DIR"
    link: "wsl"
  - name: "public_html"               # local web
    link: "windows"
  - name: "src"                       # source code
    windows_icon: "%USERPROFILE%\\.local\\share\\pixmaps\\folder_src.ico,0"
  - name: "tmpl"                      # WARN: In dotfiles, DO NOT LINK
    xdg: "XDG_TEMPLATES_DIR"
  - name: "videos"                    # videos
    xdg: "XDG_VIDEOS_DIR"
    windows_guid: "18989B1D-99B5-455B-841C-AB7C74E4DDFC"
    windows_icon: "%SystemRoot%\\system32\\imageres.dll,-189"
    link: "wsl"
  - name: "vm"                        # virtual machines
    link: "wsl"
  # NOTE: On Windows 11 My Documents live in OneDrive, in order to keep
  # OneDrive deleted My Documents needs to be relocated.
  - name: "windocs"                   # my documents
    windows_guid: "FDD39AD0-238F-46AF-ADB4-6C85480369C7"
    windows_icon: "%USERPROFILE%\\.local\\share\\pixmaps\\folder_windocs.ico,0"
    os: "windows"

# Google Drive symlinks
# Symlinks to directories and files inside Google Drive to HOME
drive_links: []

# WSL native directories
# NOTE: These need to be on native WSL filesystem in case HOME is on NTFS
wsl_native_dirs:
  - src: "/home/{{ my_user.username }}/.ssh/ctrl"
    dest: "{{ my_user.home }}/.ssh/ctrl"
    mode: "0700"
