---
# OS role variables

# APT repository sources and essential packages to install
apt_repositories:
  # Neovim
  - name: "ppa_neovim"
    key_id: "55F96FCF8231B6DD"
    sources:
      - "deb http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu {{ ansible_distribution_release }} main"
  # Git
  - name: "ppa_gitcore-git"
    key_id: "A1715D88E1DF1F24"
    sources:
      - "deb http://ppa.launchpad.net/git-core/ppa/ubuntu {{ ansible_distribution_release }} main"
  # Go
  - name: "ppa_longsleep-golang"
    key_id: "F6BC817356A3D45E"
    sources:
      - "deb http://ppa.launchpad.net/longsleep/golang-backports/ubuntu {{ ansible_distribution_release }} main"
  # Node.js:
  - name: "nodejs"
    key_id: "1655A0AB68576280"
    sources:
      # Node.js LTS (16.x)
      - "deb https://deb.nodesource.com/node_16.x/ {{ ansible_distribution_release }} main"
      - "deb-src https://deb.nodesource.com/node_16.x/ {{ ansible_distribution_release }} main"
  # LLVM
  - name: "llvm"
    key_id: "15CF4D18AF4F7421"
    sources:
      - "deb http://apt.llvm.org/{{ ansible_distribution_release }}/ llvm-toolchain-{{ ansible_distribution_release }} main"
      - "deb-src http://apt.llvm.org/{{ ansible_distribution_release }}/ llvm-toolchain-{{ ansible_distribution_release }} main"
  # PostgreSQL
  - name: "postgres"
    key_id: "7FCC7D46ACCC4CF8"
    sources:
      - "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
  # Docker
  - name: "docker"
    key_id: "8D81803C0EBFCD88"
    sources:
      - "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  # Ansible
  - name: "ppa_ansible"
    key_id: "6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367"
    sources:
      - "deb https://ppa.launchpadcontent.net/ansible/ansible/ubuntu {{ ansible_distribution_release }} main"
  # Kubernetes
  - name: "kubernetes"
    key_id: "B53DC80D13EDEF05"
    # NOTE: There is no newer APT dist than yakkety
    sources:
      - "deb http://apt.kubernetes.io/ kubernetes-yakkety main"
  # Google Cloud SDK
  - name: "gcloud"
    key_id: "B53DC80D13EDEF05"
    sources:
      - "deb https://packages.cloud.google.com/apt cloud-sdk main"

# Essential packages to install
apt_packages:
  #- snapd                    # DO NOT add snapd here
  - acl                       # manage filesystem access lists
  - apt-transport-https       # https support for APT
  - bpfcc-tools               # BPF compiler collection
  - bpftrace                  # BPF tracing analyzer
  - cryptsetup-bin
  - cpuid
  - curl
  - dosfstools
  - dnsutils                  # dig
  - equivs
  - fakeroot                  # simulate running as root
  - gawk
  - gdisk
  - git
  - git-lfs
  - gnupg
  - gzip
  - htop
  - icdiff                    # side by side diff
  - ipcalc                    # IP address/mask/subnet arithmetics calculator
  - jq                        # JSON parser and query language
  - less
  - lftp
  - logrotate
  - lsof                      # list open files
  - procps                    # /proc utilities
  - ltrace
  - m4                        # macro processor
  - make
  - mosh                      # mobile shell
  - mtr                       # traceroute & ping
  - neovim
  - netperf                   # network speed meter
  - net-tools                 # netstat & co.
  - nmap
  - openssh-client
  - p7zip
  - psmisc
  - pv                        # progressbar
  - pwgen
  - python3
  - python3-winrm             # required to Ansible-remote to Windows
  - rclone
  - rsnapshot
  - rsync
  - shellcheck                # lint shell scripts
  - socat
  - sshfs                     # mount filesystems over ssh and fuse
  - sqlite3
  - squashfs-tools
  - strace
  - stress-ng                 # stress test system (load)
  - telnet
  - tmux
  - tshark                    # network traffic capture and analysis
  - unzip
  - wdiff
  - wget
  - xdelta3
  - xz-utils
  - zip
  - unzip
  - zsh
  - powertop                  # power management utility
  - lm-sensors

apt_packages_unwanted:
  - command-not-found
  - command-not-found-data
  - motd-news-config
  - popularity-contest
  - show-motd
  - ufw                       # Ubuntu firewall?
  - update-motd

windows_packages:
  # TODO:
  - { name: totalcommaneder, params: "/InstallPath:C:\\Program Files\\TC /ShellExtension" }
  - { name: irfanview }
  - { name: irfanviewplugins }
  - { name: 7zip }
  - { name: git, params: "/GitOnlyOnPath /NoShellIntegration /WindowsTerminal", install_args: "/DIR='C:\\Devel\\git'" }
  - { name: msys2, params: "/InstallDir:C:\\Devel\\msys2" }
  - { name: sysinternals, params: "/InstallDir:C:\\Utils\\sysinternals" }

windows_envvars: {}

windows_path:
  - "C:\\Utils\\sysinternals"

# Windows registry keys (HKLM)
windows_registry:
  # Shorter shutdown/restart kill timeout
  - path: "SYSTEM\\CurrentControlSet\\Control"
    name: "WaitToKillServiceTimeout"
    data: "500"
    type: "string"
  # NOTE: These are relevant only on systems that have CDROM
  # Disable CD drive power off
  - path: "SYSTEM\\CurrentControlSet\\Services\\cdrom\\Parameters"
    name: "ZeroPowerODDEnabled"
    data: 0x00000000
    type: "dword"
  # Disable CD burning in Explorer.exe
  - path: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer"
    name: "NoCDBurning"
    data: 0x00000001
    type: "dword"
  # Enable user's mapped drive access for Administrator
  - path: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System"
    name: "EnableLinkedConnections"
    data: 0x00000001
    type: "dword"

# Windows trusted hosts (Internet Settings control panel)
# NOTE: This allows executing .exe's from Samba, etc.
windows_trusted_hosts:
  - domain: blami.net
    host: fs.lan
    protocol: file
