#!/bin/zsh
# ~/.zsh/functions/cwdellipse - output ellipsized current working directory

# Usage: cwdellipse MAXLEN
# Where MAXLEN is maximal length (in path components) to NOT be ellipsized.

cwdellipse () {
    local MAXLEN=${1:-3}

    local cwd=${PWD/$HOME/\~}
    [ -L $HOME ] && cwd=${cwd/$(readlink -m $HOME)/\~}

    if [ $MAXLEN -eq 0 ]; then
        echo $cwd
        return
    fi

    local cwd_list=(${(@s:/:)cwd})
    if [ ${#cwd_list} -gt $MAXLEN ]; then
        case ${cwd_list[1]} in
            "~")    cwd="~.." ;;
            *)      cwd="/.." ;;
        esac
        cwd="${cwd}${cwd_list[-2]}/${cwd_list[-1]}"
    fi
    echo $cwd
}

cwdellipse $@
