#!/usr/bin/zsh
# ~/.zsh/funcs/motd - Print MOTD

# Usage: motd [/path/to/db]

zmodload zsh/mapfile

# TODO Maybe come up with some caching mechanism, but this itself is fast
# enough and called once on login...
# TODO Add colors...
motd () {
    [ -r $1 ] || return
    local color

    local lines=( "${(f)mapfile[$1]}" )
    # Local database of fortunes
    local db
    local msg
    db=()
    for line in $lines; do
        if [ "${line// /}" = "%" ]; then
            [ ! -z "$msg" ] && db+=($msg)
            msg=
            continue
        fi
        [ -z "$msg" ] && msg="$line" || msg="$msg\n$line"
    done

    # Pick random quote
    msg=$db[${RANDOM}%${#db}+1]
    print $msg
}

motd $@
