#!/usr/bin/zsh
# ~/.zsh/funcs/termcolors - Change terminal colors using escape sequences

# Usage: termcolors /path/to/theme [variant]

termcolors () {
    # TODO Add support for screen/tmux and disable linux, vt100 and vt220
    # TODO When invoked without parameters print test pattern

    if [ $# -lt 1 ]; then
        (>&2 echo "error: path to colortheme must be provided")
    fi

    # NOTE If variant is not provided first found will be used
    local selected_variant=$2

    local variant key color unused
    while read -r variant key color unused; do
        # Skip commented out and empty lines
        [ -z "$variant" ] || [ "${variant:0:1}" = "#" ] && continue
        if [ -z "$key" ] || [ -z "$color" ]; then
            (>&2 echo "error: invalid record: '$variant...', skipping")
            continue
        fi
        [ -z $selected_variant ] && selected_variant=$variant
        if [ "$variant" = "$selected_variant" ]; then
            # TODO check f3 is rgb:aa/bb/cc or #rrggbb

            if [[ "$key" =~ "^(fg|bg|c|[0-9]|1?[1-9][0-9]|2[0-4][0-9]|25[0-5])$" ]]; then
                case "$key" in
                    "fg")   printf "\033]10;$color\033\\"      ;;
                    "bg")   printf "\033]11;$color\033\\"      ;;
                    "c")    printf "\033]12;$color\033\\"      ;;
                    *)      printf "\033]4;$key;$color\033\\"   ;;
                esac
            else
                (>&2 echo "error: invalid key '$key', skipping")
                continue
            fi
        fi
    done <$1
}

termcolors $@
